const toki = [
'<i>a a a! </i>:: Hahaha! (laughter)',
'<i>a a a! ni li musi </i>:: Hahaha! That\'s funny',
'<i>a a a! sina nasa </i>:: Hahaha! You\'re crazy',
'<i>a! akesi li wile moku e mi! </i>:: Ahh! The dinosaur wants to eat me!',
'<i>a </i>:: [interj] ahh, ha!, umm, hmm, ooh, well, wow, ah! aw! (emotion word)',
'<i>akesi linja ko ma </i>:: worm',
'<i>akesi linja </i>:: snake, rope-like reptiles',
'<i>akesi li pana e telo moli </i>:: The snake emitted venom ("deadly fluid")',
'<i>akesi </i>:: [n] non-cute animal, reptile, amphibian, dinosaur, monster',
'<i>akesi pi telo moli </i>:: venomous snakes, poisonous frogs ',
'<i>ala li jaki </i>:: Nothing is dirty',
'<i>ala </i>:: [mod] no, not, none, un-  [n] nothing; a state of nothingness, negation, zero  [interj] no! ',
'<i>alasa </i>:: [v]to hunt; to gather food, resources or material; to harvest; to search; to look for',
'<i>ale li jo e tenpo </i>:: There is a time for everything; everything in its right context',
'<i>ale li pona </i>:: All is good; life is beautiful; everything will be OK; I\'m in peace; I feel calm',
'<i>ali (ale) </i>:: [n]everything, all, anything, life, the universe  [mod] all, every, complete, whole ("ale" has been deprecated for phonetic reasons; "ali" is the most common word in use)',
'<i>a. mi sona </i>:: Oh, I understand',
'<i>anpa lawa </i>:: throat, neck (bottom of head) ',
'<i>anpa </i>:: [n] ground, bottom, floor, under, beneath  [mod] low, deep, defeated  [v] to lower, to defeat, to challenge, to overcome',
'<i>anpa pi sinpin lawa </i>:: chin ',
'<i>ante la </i>:: on the other hand, otherwise',
'<i>ante li kama </i>:: Change comes; times change',
'<i>ante </i>:: [n] difference  [mod] different, other  [cont] otherwise, or else  ',
'<i>anu </i>:: [conj] or',
'<i>apeja </i>:: [unofficial] disgrace, shameful. (apeja ala = honor)',
'<i>a! sina jo e noka suli! </i>:: Oh! You have big feet!',
'<i>a! sina lukin ala lukin e ijo nasa ni? </i>:: Whoa! Do you see that weird thing? ',
'<i>a! telo sijelo loje li kama tan nena kute mi!  </i>:: Ahh! Blood is coming from my ear! ',
'<i>awen e jaki </i>:: to clean',
'<i>awen pona </i>:: patient',
'<i>awen sona </i>:: remember, keep in mind',
'<i>awen </i>:: [v] to stay, pause, wait, remain, keep  [mod] remaining, stationary, permanent, sedentary, protect',
'<i>en </i>:: [conj] and (used to coordinate head nouns)',
'<i>e </i>:: [sep] (introduces a direct object)',
'<i>esun kala </i>:: fish market',
'<i>esun kili </i>:: fruit, vegetable market',
'<i>esun mani </i>:: stock market',
'<i>esun </i>:: [n] market, shop, trading place, bazaar, store, social gathering, fair',
'<i>ijo ike li lon monsi mi </i>:: Bad things are behind me',
'<i>ijo li lon oko mi </i>:: Something is in my eye',
'<i>ijo li lukin e mi </i>:: Something is watching me',
'<i>ijo lon tomo </i>:: household things ',
'<i>ijo nasa pi kasi lipu nasa </i>:: weed (drugs)',
'<i>ijo ni li wile e mani lili </i>:: This thing is cheap',
'<i>ijo </i>:: [n] thing, something, stuff, anything, object  [mod] of something  [v] objectify',
'<i>ijo uta walo </i>:: teeth ',
'<i>ike la </i>:: badly, unfortunately',
'<i>ike li kama </i>:: Bad comes; shit happens   ',
'<i>ike lukin </i>:: ugly ',
'<i>ike </i>:: [mod] bad, evil, wrong, evil, overly complex, (figuratively) unhealthy  [interj] oh dear! woe! alas!  [n] negativity, evil, badness  ',
'<i>ike! </i>:: Oh no!, Uh oh!, Alas! ',
'<i>I like plants </i>:: kasi li pona tawa mi ',
'<i>ilo kipisi </i>:: knife',
'<i>ilo kute </i>:: headphones',
'<i>ilo lape </i>:: sleeping pill ',
'<i>ilo lape soweli </i>:: animal tranquilizer or anesthetic, such as ketamine ',
'<i>ilo li lon poki </i>:: The tools are in the container',
'<i>ilo li pakala </i>:: The tool is broken',
'<i>ilo lukin lili </i>:: microscope',
'<i>ilo lukin weka </i>:: telescope',
'<i>ilo moku </i>:: eating utensil (fork/spoon/knife)',
'<i>ilo musi </i>:: toy, thing used for entertainment',
'<i>ilo nanpa </i>:: computer ',
'<i>ilo nanpa lili </i>:: calculator',
'<i>ilo nanpa tawa </i>:: laptop (see "ilo nanpa")',
'<i>ilo nasa </i>:: drugs ',
'<i>ilo nasa wawa </i>:: energy-giving drug, such as amphetamine ',
'<i>ilo ni li pilin lete </i>:: This axe feels cold',
'<i>ilo </i>:: [n] tool, device, machine, thing used for a specific purpose',
'<i>ilo oko pi suno </i>:: sunglasses',
'<i>ilo oko </i>:: spectacles, binocle, microscope, telescope, glasses (see "ilo lukin")',
'<i>ilo pi kule mun pi seli moli </i>:: ash',
'<i>ilo pi sitelen tawa </i>:: television, TV',
'<i>ilo pi sitelen toki </i>:: pen, pencil ',
'<i>ilo sitelen </i>:: tool used for writing or creating images; camera; pencil; an artist\'s paint',
'<i>ilo sona </i>:: smart tool or machine, such as a computer (see "ilo nanpa")',
'<i>ilo suno </i>:: a tool of light, lamp, flashlight  ',
'<i>ilo tawa pi telo loje pi sijelo insa </i>:: heart',
'<i>ilo tenpo </i>:: clock, watch, time machine',
'<i>ilo toki </i>:: communications device, such as a telephone, online chat ',
'<i>ilo unpa </i>:: sex toy ',
'<i>ilo wan ma </i>:: Internet ',
'<i>ilo wawa li lon ma ni </i>:: Somewhere on this island is a power source',
'<i>Inli </i>:: England, English ',
'<i>insa </i>:: [n] inside, inner world, centre, stomach  [mod] internal, central ',
'<i>Intonesija </i>:: Indonesia, Indonesian ',
'<i>Isale </i>:: Israel',
'<i>Isilan </i>:: Iceland, Icelandic ',
'<i>Italija </i>:: Italy, Italian',
'<i>jaki ala </i>:: clean, not dirty',
'<i>jaki </i>:: [mod] dirty, nasty, gross, filthy  [n] dirt, trash, pollution, filth  [v] pollute',
'<i>Jamanija </i>:: Yemen',
'<i>jan ala li toki </i>:: Nobody is talking',
'<i>jan alasa </i>:: harvester, hunter, gatherer, seeker',
'<i>jan ale li lon seme? </i>:: Where did everyone go?',
'<i>jan ali li wile tawa </i>:: Everybody wants to travel',
'<i>jan Ana o pana e moku tawa mi </i>:: Ana, give me food',
'<i>jan Epi o a! </i>:: Oh Abbie! ',
'<i>jan esun </i>:: business person, trader',
'<i>jan Eta li jan unpa </i>:: Heather is a prostitute',
'<i>jan ike </i>:: bad person, jerk, negative person, enemy ',
'<i>jan ike li kama la o seli e lipu ni </i>:: If the enemy comes, burn these papers',
'<i>jan ike li utala e ona mute </i>:: An enemy is attacking them',
'<i>jan ike lon anpa </i>:: Bad people live defeated',
'<i>jan ike ni li jo e len nasa </i>:: That bad person has strange clothes',
'<i>jan ike pi telo suli </i>:: pirate',
'<i>jan kala </i>:: mermaid',
'<i>jan Kanata </i>:: Canadian person ',
'<i>jan Keli o, sina pona lukin </i>:: Kelly, you are pretty ',
'<i>jan Ken o, mi olin e sina </i>:: Ken, I love you ',
'<i>jan Ken o, pipi li lon len sina </i>:: Ken, a bug is on your shirt ',
'<i>jan kulupu </i>:: member of a group',
'<i>jan laso jelo lili li kama tan sewi </i>:: A little green person came from the sky',
'<i>jan lawa </i>:: leader, boss, master, chairperson, president, director ',
'<i>jan lawa li moku e telo jaki </i>:: The leader drank dirty water',
'<i>jan lawa ma </i>:: president of country, governor of state, premier of province ',
'<i>jan lawa pi jan utala </i>:: leader of soldiers (commander, general) ',
'<i>jan lawa pi ma tomo </i>:: mayor ',
'<i>jan lawa pi tomo tawa kon </i>:: leader of airplanes, a pilot ',
'<i>jan lawa pi tomo tawa telo li moku </i>:: The captain of the ship is eating',
'<i>jan li ken kama tawa pini kepeken nasin pona! </i>:: Some winners are bigger than other winners!',
'<i>jan lili </i>:: child, daughter, son  ',
'<i>jan lili en jan suli li toki </i>:: The child and the adult are talking ',
'<i>jan lili li ken ala moku e telo nasa </i>:: Children can\'t drink beer',
'<i>jan lili li lukin e jan suli </i>:: Children watch adults',
'<i>jan lili li sona ala e ike </i>:: Children are innocent',
'<i>jan lili li wile e telo kili </i>:: Children want fruit juice ',
'<i>jan lili pi jan Keli li musi </i>:: Keli\'s child is funny',
'<i>jan lili pi jan Ken en jan Lisa li suwi </i>:: Ken and Lisa\'s baby is sweet',
'<i>jan lili sina li suwi </i>:: Your baby is cute',
'<i>jan lili </i>:: small, short, thin or young person, child ',
'<i>jan lili tu wan </i>:: 3 children ',
'<i>jan li lon insa tomo </i>:: Somebody\'s inside the house',
'<i>jan li lukin sama pipi </i>:: People look like ants',
'<i>jan li moku </i>:: Somebody is eating',
'<i>jan li moli e waso </i>:: The person killed the bird ',
'<i>jan li moli </i>:: People are murderers',
'<i>jan li pona </i>:: People are good',
'<i>jan Lisa li pona </i>:: Lisa is cool',
'<i>jan Lisa o, toki </i>:: Hello, Lisa',
'<i>jan Lisa taso li kama </i>:: Only Lisa came ',
'<i>jan li seme? </i>:: People are what? Who are they?',
'<i>jan li suli mute. mani li suli lili </i>:: People are more important than money',
'<i>jan li toki kepeken toki pona lon tomo toki </i>:: People talk using Toki Pona in the chat room',
'<i>jan li wile jo e ma </i>:: People want to own land ',
'<i>jan luka tu </i>:: 7 people',
'<i>jan Mawen o, sina wile ala wile moku? </i>:: Marvin, are you hungry? ',
'<i>jan Mesiko </i>:: Mexican person ',
'<i>jan Mewi li toki tawa mi </i>:: Mary\'s talking to me',
'<i>jan moli </i>:: dead man, zombie',
'<i>jan Mose o lawa e mi mute tawa ma pona </i>:: Moses, lead us to the good land',
'<i>jan mute li kama </i>:: Many people are coming',
'<i>jan mute lili li kama </i>:: Some people are coming',
'<i>jan mute mute mute li kama! </i>:: Many, many, many people are coming! ',
'<i>jan namako </i>:: extras in a movie, people acting as decoration or performing',
'<i>jan nasa </i>:: strange, foolish, unconventional or crazy person, drunk person, alcoholic',
'<i>jan nasa utala </i>:: fighting fool',
'<i>jan Nesan li musi </i>:: Nathan is funny ',
'<i>jan ni li pona lukin </i>:: That person is pretty ',
'<i>jan ni li sama mi </i>:: That person is like me',
'<i>jan </i>:: [n] person, people, human, being, somebody, anybody, in  [mod] personal, human, somebody\'s, of people  [v] personify, humanize, personalize ',
'<i>jan olin </i>:: loved one, significant other, partner',
'<i>jan pakala </i>:: disabled person, an injured person, victim',
'<i>jan pali li pona e supa jaki </i>:: The servants cleaned the carpet',
'<i>jan pali </i>:: worker, employee',
'<i>jan Pawe o, mi wile ala moli </i>:: Forrest, I don\'t want to die',
'<i>jan Pentan li pana e sona tawa mi </i>:: Brandon teaches me',
'<i>jan pi ike lukin </i>:: an ugly person ',
'<i>jan pi jan unpa mute </i>:: promiscuous person',
'<i>jan pi kama sona </i>:: student',
'<i>jan pi ma ante </i>:: foreigner, immigrant',
'<i>jan pi ma sama </i>:: fellow citizen of same country or land ',
'<i>jan pi ma tomo </i>:: person of the city, a city-dweller ',
'<i>jan pi musi sijelo </i>:: athlete ',
'<i>jan pi nanpa tu tu </i>:: 4th person ',
'<i>jan pi nanpa wan li lon </i>:: The first person is here',
'<i>jan pi nasin sewi Kolisu </i>:: person of Christian religion, a Christian ',
'<i>jan (pi pali) moku </i>:: chef, cook ',
'<i>jan (pi pali) unpa </i>:: sex worker, prostitute, whore, bitch',
'<i>jan pi pana sona </i>:: teacher',
'<i>jan pi pona lukin </i>:: an attractive person',
'<i>jan pi pona pilin </i>:: psychotherapist',
'<i>jan pi pona sijelo </i>:: doctor, healer ',
'<i>jan pi sona oko </i>:: oculist, eye doctor, optometrist',
'<i>jan pi tomo pali </i>:: office worker',
'<i>jan pi tomo sama </i>:: housemate, roommate ',
'<i>jan pi wawa ala </i>:: a weak person ',
'<i>jan poka </i>:: neighbor, someone who is beside you ',
'<i>jan pona </i>:: good person, friend, positive or good person',
'<i>jan pona mi li lon poka mi </i>:: My friend is beside me',
'<i>jan sama </i>:: similar person, counterpart, peer, person in same situation, sibling, brother, sister',
'<i>jan San li seme? </i>:: Who is John? ',
'<i>jan San o, </i>:: John, ',
'<i>jan San o tawa tomo sina!  </i>:: John, go to your house! ',
'<i>jan Santa </i>:: Santa Claus ',
'<i>jan seme li jo e poka mi pi kalama musi? </i>:: Who has my mp3 player? (container of music)',
'<i>jan seme li lon ni? </i>:: Who is there?  ',
'<i>jan seme li lon? </i>:: Who\'s there?',
'<i>jan seme li meli sina?  </i>:: Who is your female partner? ',
'<i>jan seme li moku? </i>:: Who is eating? ',
'<i>jan seme li olin e sina? </i>:: Who loves you?  ',
'<i>jan seme li tawa poka sina? </i>:: Who went with you? ',
'<i>jan seme pi kulupu ni li suli? </i>:: Which people of this group are important?  ',
'<i>jan Sesi o moku e kili ni </i>:: Jessie, eat this fruit',
'<i>jan sewi </i>:: God; Divinity; any sentient, real or non-extant, considered divine',
'<i>jan sin li kama ala kama? </i>:: Are more people coming?  ',
'<i>jan sin li kama </i>:: More people are coming',
'<i>jan sona </i>:: knowledgeable person, wise person, educated person, academic, specialist ',
'<i>jan sona li jan nasa </i>:: A wise man is a fool; a genius thinks unconventionally',
'<i>jan sona nanpa </i>:: mathematician ',
'<i>jan sona pilin </i>:: psychologist ',
'<i>jan sona sijelo </i>:: doctor, physician ',
'<i>jan suli </i>:: big, tall or fat person, adult ',
'<i>jan Susan anu jan Lisa li moku e suwi? </i>:: Susan or Lisa ate the cookies? ',
'<i>jan Susan li nasa </i>:: Susan is crazy',
'<i>jan Ta o toki ala tawa mi </i>:: Todd, don\'t talk to me ',
'<i>jan Tepani o, sina ike tawa mi </i>:: Steffany, I don\'t like you ',
'<i>jan toki </i>:: speaker, messenger, person communicating, spokesman',
'<i>jan unpa </i>:: lover, sexual partner, nymphomaniac',
'<i>jan utala ali li nasa </i>:: All soldiers are stupid',
'<i>jan utala li seli ala seli e tomo?  </i>:: Is the warrior burning the house? ',
'<i>jan utala nasa mute </i>:: many stupid soldiers  ',
'<i>jan utala nasa ni </i>:: this stupid soldier  ',
'<i>jan utala nasa </i>:: stupid soldier',
'<i>jan utala pi ma Mewika li ike tawa ma ali </i>:: Soldiers of the USA are bad for the world',
'<i>jan utala </i>:: soldier, warrior, assassin',
'<i>jan Wasintan li jan lawa pona pi ma Mewika </i>:: Washington was a good leader of America ',
'<i>jan wawa </i>:: strong person ',
'<i>jelo </i>:: [mod] yellow, light green',
'<i>jo ala e selo lon pini palisa </i>:: to be circumsized',
'<i>jo e linja mute </i>:: to be hairy ',
'<i>jo e mani mute </i>:: to be rich ',
'<i>jo e pilin pona </i>:: to have positive feelings, be mentally healthy ',
'<i>jo e selo lon pini palisa </i>:: uncircumcised, uncut ',
'<i>jo e sijelo pona </i>:: to be (physically) healthy ',
'<i>jo ijo li ike e jan </i>:: Possession corrupts',
'<i>jo </i>:: [v] to have, contain  [n] ownership, posession, having',
'<i>kala </i>:: fish or an animal that lives in the water, seafood',
'<i>kala kalama </i>:: noisy fish, any variety of noisy fish, the category of fish that makes audible noises, such as the dog fish',
'<i>kala kiwen kepeken insa moku </i>:: edible mollusk',
'<i>kala kiwen loje </i>:: crab or lobster',
'<i>kala kiwen </i>:: mollusks, lobsters, barnacles and other sea creatures with exoskeletons',
'<i>kala kiwen pimeja </i>:: mussel',
'<i>kala kulupu jan </i>:: pescine community of people, such as a fishing village or fisherman\'s trade union',
'<i>kala kulupu </i>:: pescine community',
'<i>kala len </i>:: fish of clothing, such as fish suitable for making Icelandic folk fish-skin shoes',
'<i>kala lete </i>:: raw fish, sushi ',
'<i>kala lili </i>:: small fish, or any variety of small fish, or the category of small fish, such as the minnow',
'<i>kala lili </i>:: small fish, or any variety of small fish, or the category of small fish, such as the minnow',
'<i>kalama ala li lon </i>:: No sound exists; silence',
'<i>kala ma </i>:: lung fish, other fish that can live out of water',
'<i>kalama musi en meli li pona tawa mi </i>:: I like music and girls ',
'<i>kalama musi "Jingle Bells" li pona tawa mi </i>:: I like the song "Jingle Bells"',
'<i>kalama musi li pona tawa mi </i>:: I like music ',
'<i>kalama musi pi jan Elton-John li nasa </i>:: The music of Elton John is odd ',
'<i>kalama musi pi jan Enja li pona </i>:: Enya\'s music is good',
'<i>kala mani </i>:: fish hunted for commercially',
'<i>kalama ni li seme? </i>:: What was that noise? ',
'<i>kalama </i>:: [n] sound, voice, noise  [v] to make noise or sound, to ring, to play an instrument',
'<i>kala moli </i>:: poisonous fish',
'<i>kala </i>:: [n] fish, sea creature ',
'<i>kala sama </i>:: camouflaged fish',
'<i>kala seli </i>:: tropical fish',
'<i>kala selo </i>:: shell fish',
'<i>kala suli </i>:: big fish, whale, shark',
'<i>kala suli pi mama soweli moli </i>:: killer whale (lit: big fish of the killer maternal cute animals)',
'<i>kala suli pi mama soweli </i>:: whale (lit: big fish of the maternal cute animals)',
'<i>kama anpa </i>:: go down, descend',
'<i>kama ante </i>:: transform, turn into, to change',
'<i>kama e </i>:: bring, fetch, carry, becomes, converts',
'<i>kama insa </i>:: come into, enter',
'<i>kama jaki ala </i>:: to clean up',
'<i>kama jo e lupa meli </i>:: to get genital reconstruction surgery as a women, such as vaginoplasty  ',
'<i>kama jo e palisa mije </i>:: to get genital reconstruction surgery as a man, such as metoidioplasty, phalloplasty ',
'<i>kama jo e sinpin lawa meli </i>:: to get facial feminization surgery ',
'<i>kama jo e sinpin mije </i>:: to get male chest reconstruction surgery ',
'<i>kama jo e telo </i>:: to get water',
'<i>kama jo </i>:: get, receive, take, obtain',
'<i>kama jo lon esun </i>:: to get at the market, pickup, buy',
'<i>kama jo </i>:: receive, get, take, obtain',
'<i>kama lili </i>:: diminish, decrease',
'<i>kama li pona tawa mi </i>:: I\'m a lucky guy',
'<i>kama </i>:: [n] event, happening, chance, arrival, beginning  [mod] coming, future  [v] come, become, arrive, happen, pursue actions to arrive to (a certain state), cause',
'<i>kama olin </i>:: fall in love with ',
'<i>kama pilin ike </i>:: get angry',
'<i>kama pi lukin ala </i>:: to hide',
'<i>kama pi lukin sin </i>:: to find',
'<i>kama pona! </i>:: Come well! Welcome! Greetings!',
'<i>kama sewi </i>:: go up, ascend',
'<i>kama sewi sin </i>:: revive, resurrect',
'<i>kama sinpin </i>:: stand up',
'<i>kama sin </i>:: rebirth, come back, return',
'<i>kama sona tan kepeken </i>:: learning by doing',
'<i>kama telo </i>:: melt',
'<i>kama wan </i>:: unite, meet',
'<i>kasi anpa </i>:: grass ',
'<i>kasi kule </i>:: flower ',
'<i>kasi kule li pona lukin </i>:: Flowers are pretty',
'<i>kasi lili </i>:: little weeds ',
'<i>kasi linja laso jelo </i>:: grass',
'<i>kasi nasa / kasi sona </i>:: weed, hemp, intoxicating plant, such as marijuana ',
'<i>kasi </i>:: [n] plant, leaf, herb, tree, wood ',
'<i>kasi pi tenpo pona Kolisu </i>:: Chrismas tree ',
'<i>kasi pona lukin li lon </i>:: It\'s a very pretty flower',
'<i>kasi suli pi nanpa mute </i>:: forest',
'<i>kasi suli </i>:: trees, big shrubs ',
'<i>kasi wawa </i>:: spice ',
'<i>ken la ilo li pakala </i>:: Maybe the tool is broken',
'<i>ken la jan lili li wile moku e telo </i>:: Maybe the baby is thirsty',
'<i>ken la jan Lisa li jo e ona </i>:: Maybe Lisa has it',
'<i>ken la jan Susan li kama </i>:: Maybe Susan will come',
'<i>ken la </i>:: maybe',
'<i>ken la mi ken tawa ma Elopa </i>:: Maybe I can go to Europe',
'<i>ken la mi sona mute! </i>:: Maybe I know a lot!',
'<i>ken la ona li lape </i>:: Maybe he\'s alseep',
'<i>ken la ona li lon tomo sona </i>:: Maybe he\'s in school',
'<i>ken </i>:: [n] possibility, ability, power to do things,  permission  [v] can, is able to, is allowed to, may, is possible  [v]  make possible, enable, allow, permit  ',
'<i>kepeken e kasi nasa </i>:: to use a non-synthetic drug',
'<i>kepeken e utala </i>:: to use violence ',
'<i>kepeken ike e ilo nasa </i>:: to abuse drugs  ',
'<i>kepeken lili e ilo nasa </i>:: to use drugs in moderation ',
'<i>kepeken </i>:: [v] use  [prep] with',
'<i>kili lili kiwen </i>:: nut ',
'<i>kili lili </i>:: small vegetable, fruit, such as berry, olive ',
'<i>kili li lon poki </i>:: The fruit is in the basket ',
'<i>kili li moku li pona </i>:: Pineapple is a food and is good',
'<i>kili li pona tawa mi </i>:: I like fruit',
'<i>kili li tawa anpa poka kasi </i>:: The apple doesn\'t drop far from the tree',
'<i>kili loje </i>:: reddish fruit or vegetable, such as a tomato ',
'<i>kili ma </i>:: earth vegetable, such as a potato ',
'<i>kili mi </i>:: my fruit ',
'<i>kili </i>:: [n] fruit, vegetable, mushroom',
'<i>kili palisa </i>:: long fruit or vegetable, such as a carrot, banana, cucumber ',
'<i>Kilipasi </i>:: Kiribati ',
'<i>kili pi jan Linta li ike </i>:: Linda\'s fruit is bad',
'<i>kili pi jan Susan </i>:: Susan\'s fruit ',
'<i>kili suwi </i>:: (sweet) fruit      ',
'<i>kin </i>:: [mod] also, too, even, indeed (emphasizes the word that follows)',
'<i>kipisi tomo </i>:: fence, wall',
'<i>kipisi </i>:: [v] to divide, to cut',
'<i>kiwen jelo li wile e mani mute </i>:: The gold is expensive',
'<i>kiwen kule </i>:: colorful metal',
'<i>kiwen linka </i>:: wire, ductile metal',
'<i>kiwen mun </i>:: moon rock',
'<i>kiwen </i>:: [n] hard thing, rock, stone, metal, mineral, clay  [mod] hard, solid, stone-like, made of stone or metal',
'<i>kiwen pakala </i>:: broken rock, gravel',
'<i>kiwen pan </i>:: day old bread',
'<i>kiwen pi sitelen insa </i>:: bone',
'<i>kiwen suwi </i>:: rock candy',
'<i>kiwen telo </i>:: lava, mercury, liquid rock',
'<i>kiwen uta </i>:: teeth',
'<i>kiwen weka </i>:: mining, to carve',
'<i>kiwen wile </i>:: desirable rocks, precious metals, gems',
'<i>ko jaki lon nena sinpin </i>:: boogers ',
'<i>ko jaki </i>:: shit, feces, pooh ',
'<i>ko lete li kama </i>:: It\'s snowing',
'<i>kon en sewi </i>:: weather ',
'<i>kon </i>:: [n] air, odour, soul, spirit, atmosphere, wind  [mod] air-like, ethereal, gaseous',
'<i>ko </i>:: [n] semi-solid substance, such as a paste, a powder, or a gum',
'<i>kon sewi li jo e walo </i>:: It\'s cloudy',
'<i>kon tawa </i>:: wind',
'<i>kon telo walo </i>:: cloud, snow, fog ',
'<i>ko (walo) wawa </i>:: cocaine ',
'<i>kule laso loje li pona tawa mi </i>:: I like the color purple',
'<i>kule lon palisa luka </i>:: nail polish',
'<i>kule namako </i>:: cosmetics, make-up, flashy colors',
'<i>kule </i>:: [n] color, paint  [v] color, paint  [mod] colourful',
'<i>kule seme li pona tawa sina? </i>:: Which color do you like?  ',
'<i>kule sewi </i>:: rainbow',
'<i>kulupu </i>:: group, community, society ',
'<i>kulupu kala </i>:: community of fish',
'<i>kulupu mama </i>:: family ',
'<i>kulupu musi </i>:: a party, a fun gathering',
'<i>kulupu </i>:: [n] group, community, society, company  [mod] communal, shared, public, of the society',
'<i>kulupu pi jan kala </i>:: community of fishermen',
'<i>kulupu pi tenpo mun </i>:: Month ',
'<i>kulupu pi tenpo suno luka tu </i>:: days of the week ',
'<i>kulupu pi toki pona </i>:: the Toki Pona community ',
'<i>kute tan kama sona. kute tan ala toki </i>:: Listen to know, don\'t listen to speak',
'<i>kute </i>:: [v] listen, hear  [mod] auditory, hearing',
'<i>lape li pona </i>:: Sleep and rest are good',
'<i>lape </i>:: [n][v] sleep, rest  [mod] sleeping, of sleep',
'<i>lape pona! </i>:: Sleep well! Have a good night!  ',
'<i>la </i>:: separates the adverb or phrase of context from the rest of the sentence',
'<i>laso jelo </i>:: green (yellowish blue) ',
'<i>laso jelo / jelo laso </i>:: yellowish blue (green) ',
'<i>laso loje / loje laso </i>:: reddish blue (purple) ',
'<i>laso loje </i>:: purple (reddish blue) ',
'<i>laso </i>:: [n][mod] blue, blue-green ',
'<i>laso pimeja </i>:: dark blue ',
'<i>lawa e pilin </i>:: to master one\'s feelings, be composed  ',
'<i>lawa </i>:: [n] main, leader, in charge, the head, the mind  [v] to lead, control, rule, steer',
'<i>len jan </i>:: somebody\'s clothes ',
'<i>len lawa </i>:: hat, hood, bonnet, headdress ',
'<i>len li lon poka mi </i>:: The clothes are at my side',
'<i>len li telo ala </i>:: The clothes are dry',
'<i>len luka </i>:: gloves, mittens',
'<i>len namako </i>:: fashion accessory',
'<i>len </i>:: [n] clothes, article of clothing, cloth, fabric ',
'<i>len ni li kule seme? </i>:: What colour is this article of clothing? ',
'<i>len noka </i>:: shoe, pants ',
'<i>len pi jan Lisa </i>:: Lisa\'s clothes ',
'<i>len pi jan Susan li jaki </i>:: Susan\'s clothes are dirty',
'<i>len pi loje en laso </i>:: shirt of red and blue ',
'<i>len sina li telo ala telo? </i>:: Are your clothes wet? ',
'<i>len supa </i>:: tablecloth',
'<i>lete lili li kin lon </i>:: Here is it little cold too',
'<i>lete lili li lon </i>:: It\'s cool',
'<i>lete li lon </i>:: It\'s cold',
'<i>lete mute li lon </i>:: It\'s very cold',
'<i>lete </i>:: [n] cold   mod cold, uncooked  [v] cool down, chill, freeze ',
'<i>letter </i>:: pronounced as in',
'<i>lili </i>:: [mod] small, little, young, a bit, short, fes, less  [v] reduce, shorten, shrink, lessen ',
'<i>linja lawa </i>:: head-hair',
'<i>linja lili oko </i>:: eyebrows, eyelashes ',
'<i>linja mi li telo </i>:: My hair is wet',
'<i>linja namako </i>:: hair extensions, hairdressing work',
'<i>linja </i>:: [n] long, very thin, floppy thing; such as a string, line, rope, hair, thread, cord, or chain ',
'<i>linja sinpin </i>:: beard, facial hair ',
'<i>linja uta </i>:: moustache ',
'<i>lipu </i>:: [n] flat and bendable thing; such as paper, a card, or a ticket',
'<i>lipu ni li pilin lete </i>:: This paper feels cold',
'<i>lipu pi tomo telo  </i>:: toilet paper',
'<i>lipu toki </i>:: paper with written information; such as a document, text, or book ',
'<i>li </i>:: [sep] placed between any subject and its verb, except when the subject is "mi" or "sina"; also used to introduce a new verb for the same subject, whether or not "mi" or "sina" is used as the subject',
'<i>loje jelo </i>:: orange (yellowish red) ',
'<i>loje laso (pimeja) </i>:: (dark) blueish red, purple ',
'<i>loje </i>:: [n][mod]red ',
'<i>loje walo </i>:: light red, pink ',
'<i>loje walo </i>:: pink (whitish red) ',
'<i>lon ala </i>:: no, zero',
'<i>lon anpa </i>:: to be beneath',
'<i>lon esun </i>:: to do business, to be trading, to be at the market',
'<i>lon ni ala </i>:: far',
'<i>lon ni </i>:: near',
'<i>lon </i>:: [prep] be located in, at, or on  [v] be there, cause to exist, awaken from sleep  [mod] be present, be real, be true  [interj] yes (used rarely)',
'<i>lon tenpo pi pali ala </i>:: to be taking a sabbatical, break from work ',
'<i>luka luka </i>:: 5 + 5 = 10 ',
'<i>luka luka luka </i>:: 5 + 5 + 5 = 15 ',
'<i>luka luka tu </i>:: 5 + 5 + 2 = 12 ',
'<i>luka luka tu tu </i>:: 5 + 5 + 2 + 2 = 14 ',
'<i>luka luka tu wan </i>:: 5 + 5 + 2 + 1 = 13 ',
'<i>luka luka wan </i>:: 5 + 5 + 1 = 11 ',
'<i>luka mi li jaki. mi wile telo e ona </i>:: My hands are dirty, I want to wash them',
'<i>luka </i>:: [n] hand, arm  [mod] five',
'<i>luka tu </i>:: 5 + 2 = 7 ',
'<i>luka tu tu </i>:: 5 + 2 + 2 = 9 ',
'<i>luka tu wan </i>:: 5 + 2 + 1 = 8 ',
'<i>luka wan </i>:: 5 + 1 = 6 ',
'<i>lukin e toki </i>:: read ',
'<i>lukin jo e pali </i>:: to be looking for a job ',
'<i>lukin </i>:: [v] see, look at, watch, read, look, watch out, pay attention  [mod] visual, vision, sight',
'<i>lupa jaki </i>:: anus ',
'<i>lupa kute </i>:: ear ',
'<i>lupa meli li mama ale </i>:: A woman\'s womb is the mother of all things',
'<i>lupa meli </i>:: vagina',
'<i>lupa monsi </i>:: anus ',
'<i>lupa nena </i>:: nostrils ',
'<i>lupa </i>:: [n] hole, orifice, window, door',
'<i>lupa ni li suli </i>:: That hole is big',
'<i>lupa pi telo jelo </i>:: urethra',
'<i>ma Akanisan </i>:: Afghanistan ',
'<i>ma Alan </i>:: Ireland ',
'<i>ma Alensina </i>:: Argentina  ',
'<i>ma ali li pona </i>:: All nations are good',
'<i>ma Amelika lete </i>:: North America',
'<i>ma Amelika seli </i>:: South America',
'<i>ma Amelika </i>:: the Americas',
'<i>ma Anku </i>:: Korea ',
'<i>ma Antasika </i>:: Antarctica',
'<i>ma Antola </i>:: Andorra',
'<i>ma Apika </i>:: Africa',
'<i>ma Asija </i>:: Asia',
'<i>ma Awisi </i>:: Haiti, Haitian Creole',
'<i>ma Ekato </i>:: Ecuador',
'<i>ma Elena </i>:: Greece',
'<i>ma Elopa </i>:: Europe',
'<i>ma Elopa li weka tan ma Mewika </i>:: Europe is away from the USA',
'<i>ma Epanja </i>:: Spain',
'<i>ma Esi </i>:: Estonia',
'<i>ma Esuka </i>:: Basque Country ',
'<i>ma Ilakija </i>:: Iraq ',
'<i>ma Ilan </i>:: Iran, Persia',
'<i>ma Inli li pona </i>:: England is good',
'<i>ma Italija li pona lukin </i>:: Italy is beautiful',
'<i>ma kala </i>:: land of the fish, fish land, the ocean',
'<i>ma Kalalinuna </i>:: Greenland, Greenlandic ',
'<i>ma Kana </i>:: Ghana',
'<i>ma Kanata </i>:: Canada',
'<i>ma Kanata li pona </i>:: Canada is good',
'<i>ma Kanse </i>:: France, French         ',
'<i>ma kasi </i>:: forest, jungle ',
'<i>ma Katala </i>:: Qatar         ',
'<i>ma Katalunja </i>:: Catalonia',
'<i>ma Katelo </i>:: Georgia ',
'<i>ma Katemala </i>:: Guatemala ',
'<i>ma Kenata </i>:: Grenada ',
'<i>ma Kepeka </i>:: Quebec',
'<i>ma Keposi </i>:: Cyprus ',
'<i>ma Kinla </i>:: Wales ',
'<i>ma Konko (pi ma tomo Kinsasa) </i>:: Congo, Democratic Republic  of',
'<i>ma Konko (pi ma tomo Pasawi) </i>:: Congo, Peoples Republic  of',
'<i>ma Kosalika </i>:: Costa Rica ',
'<i>ma Kosiwa </i>:: Côte d\'Ivoire ',
'<i>ma Kupa </i>:: Cuba',
'<i>ma Kusala </i>:: Gujarat  ',
'<i>ma Kuwasi </i>:: Kuweit ',
'<i>ma Lanka </i>:: Sri Lanka ',
'<i>ma Lesi </i>:: Brittany  ',
'<i>ma li lon anpa mi </i>:: The land is beneath me ',
'<i>ma Lipija </i>:: Libya ',
'<i>ma li pona lukin </i>:: The countryside is good to look at',
'<i>ma Lisensan </i>:: Liechtenstein ',
'<i>ma Lomani </i>:: Romania',
'<i>ma lon telo </i>:: island ',
'<i>ma Losi </i>:: Russia ',
'<i>ma Lowasi </i>:: Croatia ',
'<i>ma Lowenki </i>:: Slovakia ',
'<i>ma Lowensina </i>:: Slovenia ',
'<i>ma Lunpan </i>:: Lebanon        ',
'<i>ma Lusepu </i>:: Luxemburg ',
'<i>ma Luwanta </i>:: Rwanda ',
'<i>ma Maketonija </i>:: Macedonia ',
'<i>ma ma kili </i>:: land of vegetables, garden',
'<i>ma ma kili </i>:: land of vegetables, garden',
'<i>ma Malakasi </i>:: Madagascar, Malagasy ',
'<i>ma Malasija </i>:: Malaysia, Malay ',
'<i>ma Malawi </i>:: Malawi ',
'<i>ma Mali </i>:: Mali ',
'<i>ma Malipe </i>:: Morocco ',
'<i>mama mama </i>:: grandparent ',
'<i>mama meli </i>:: mother ',
'<i>mama meli o awen </i>:: Mama, wait',
'<i>mama mije </i>:: father ',
'<i>mama mi li moli la mi pilin ike </i>:: I feel bad because my parents died',
'<i>mama </i>:: [n] parent, creator, founder [mod] maternal, fatherly, parental',
'<i>mama ona li kepeken e kasi nasa </i>:: His mother used pot',
'<i>ma Masija </i>:: Hungary, Hungarian ',
'<i>ma Masu </i>:: Egypt ',
'<i>ma Mesiko </i>:: Mexico ',
'<i>ma Mewika li weka ala tan ma Kupa </i>:: The USA is not far away from Cuba',
'<i>ma Mewika </i>:: USA, American ',
'<i>ma Mijama </i>:: Myanmar',
'<i>ma mi li pimeja </i>:: My land is dark',
'<i>ma Motowa </i>:: Moldova         ',
'<i>ma Mulitanija </i>:: Mauritania ',
'<i>ma Namipija </i>:: Namibia ',
'<i>ma Naselija </i>:: Nigeria ',
'<i>ma Netelan </i>:: Netherlands, Dutch ',
'<i>ma Nijon </i>:: Japan, Japanese ',
'<i>mani lipu </i>:: credit card, visa, mastercard',
'<i>mani namako </i>:: excess money',
'<i>mani nanpa </i>:: digital money, bitcoin',
'<i>mani </i>:: [n] money, material wealth, currency, dollar, capital',
'<i>mani pi ma ante li pona tawa mi </i>:: I like currency of other nations',
'<i>ma Nise </i>:: Niger ',
'<i>ma </i>:: [n] land, earth, country, (outdoor) area, ecology, region, outside area',
'<i>ma Nosiki </i>:: Norway, Norwegian Bokmål ',
'<i>ma Nusilan </i>:: New Zealand ',
'<i>ma ona </i>:: her country ',
'<i>ma Ontula </i>:: Honduras ',
'<i>ma Osalasi </i>:: Austria ',
'<i>ma Oselija </i>:: Australia ',
'<i>ma Pakisan </i>:: Pakistan ',
'<i>ma Palakawi </i>:: Paraguay ',
'<i>ma Palani </i>:: Bahrein ',
'<i>ma Palata </i>:: India ',
'<i>ma Panama </i>:: Panama ',
'<i>ma Panla </i>:: Bangladesh, Bengali ',
'<i>ma Papeto </i>:: Barbados ',
'<i>ma Papuwanijukini </i>:: Papua New Guinea ',
'<i>ma Pasila </i>:: Brasil ',
'<i>ma Pawama </i>:: Bahamas ',
'<i>ma Pelalusi </i>:: Belarus, Belarussian ',
'<i>ma Pelu </i>:: Peru ',
'<i>ma Pemuta </i>:: Bermuda ',
'<i>ma Penesuwela </i>:: Venezuela ',
'<i>ma Penin </i>:: Benin ',
'<i>ma Pesije </i>:: Belgium ',
'<i>ma pi jan Keli </i>:: Keli\'s country ',
'<i>ma Pilipina </i>:: Philipines ',
'<i>ma Pilisin </i>:: Palestine ',
'<i>ma Pisi </i>:: Fiji ',
'<i>ma Piten </i>:: Britain, UK',
'<i>ma Pokasi </i>:: Bulgaria, Bulgarian ',
'<i>ma Posan </i>:: Bosnia and Herzegovina ',
'<i>ma Posuka </i>:: Poland ',
'<i>ma Potuke </i>:: Portugal ',
'<i>ma Samalino </i>:: San Marino ',
'<i>ma Sameka </i>:: Jamaica',
'<i>ma Samowa </i>:: Samoa ',
'<i>ma Sasali </i>:: Algeria',
'<i>ma Sawa </i>:: Java',
'<i>ma Sawasi </i>:: Swaziland ',
'<i>ma Seki </i>:: Czech Republic ',
'<i>ma seme li pona tawa sina? </i>:: Which countries do you like? ',
'<i>ma Seneka </i>:: Senegal ',
'<i>ma Setapika </i>:: South Africa ',
'<i>ma sike </i>:: planet',
'<i>ma sike suli </i>:: planet',
'<i>ma Sile </i>:: Chile',
'<i>ma sina </i>:: your country ',
'<i>ma Sinita </i>:: Trinidad and Tobago',
'<i>ma Sipusi </i>:: Djibouti ',
'<i>ma Sonko </i>:: China',
'<i>ma Sopisi </i>:: Serbia ',
'<i>ma Sukosi </i>:: Scotland',
'<i>ma Sulija </i>:: Syria ',
'<i>ma Sumi </i>:: Finland',
'<i>ma Sutan </i>:: Sudan',
'<i>ma Suwasi </i>:: Switzerland, Swiss',
'<i>ma Tansi </i>:: Denmark',
'<i>ma Tawi </i>:: Thailand, Thai',
'<i>ma telo </i>:: mud, swamp ',
'<i>ma Toko </i>:: Togo ',
'<i>ma Tominika </i>:: Dominican Republic ',
'<i>ma tomo Akajela </i>:: Cairo (Egypt) ',
'<i>ma tomo Alana </i>:: Atlanta (USA) ',
'<i>ma tomo Alawa </i>:: Ottawa (Canada) ',
'<i>ma tomo Alenta </i>:: Atlanta',
'<i>ma tomo Alipasi </i>:: Halifax (Canada) ',
'<i>ma tomo Anpu </i>:: Hamburg (Germany) ',
'<i>ma tomo Ansetan </i>:: Amsterdam (Netherlands) ',
'<i>ma tomo Asina </i>:: Athens (Greece) ',
'<i>ma tomo </i>:: city, town ',
'<i>ma tomo Ele </i>:: Los Angeles (USA) ',
'<i>ma tomo Esupo </i>:: Espoo (Finland) ',
'<i>ma tomo Iwesun </i>:: Hilversum (Netherlands)  ',
'<i>ma tomo Kakawi </i>:: Calgary (Canada) ',
'<i>ma tomo Kenpisi </i>:: Cambridge (USA, GB) ',
'<i>ma tomo Kunte </i>:: Bangkok (Thailand) ',
'<i>ma tomo Lantan li suli </i>:: London is big',
'<i>ma tomo Lanten </i>:: London (England)  ',
'<i>ma tomo lawa </i>:: capital ',
'<i>ma tomo Lesinki </i>:: Helsinki (Finland) ',
'<i>ma tomo Loma </i>:: Rome (Italy) ',
'<i>ma tomo Manten </i>:: Moncton (Canada) ',
'<i>ma tomo Mesiko </i>:: Mexico City (Mexico) ',
'<i>ma tomo Milano </i>:: Milan (Italy) ',
'<i>ma tomo Minsen </i>:: Munich (Germany) ',
'<i>ma tomo Monkela </i>:: Montreal (Canada) ',
'<i>ma tomo Napoli </i>:: Naples (Italy) ',
'<i>ma tomo Nujoka </i>:: New York City (USA) ',
'<i>ma tomo Osaka </i>:: Osaka (Japan)  ',
'<i>ma tomo Paki </i>:: Paris (France) ',
'<i>ma tomo Pasen </i>:: Boston (USA) ',
'<i>ma tomo Pelin </i>:: Berlin ',
'<i>ma tomo Pelin </i>:: Berlin (Germany) ',
'<i>ma tomo Peminan </i>:: Birmingham (England)  ',
'<i>ma tomo Pesin </i>:: Beijing, Peking (China) ',
'<i>ma tomo Pilense </i>:: Florence (Italy) ',
'<i>ma tomo Polan </i>:: Portland (USA) ',
'<i>ma tomo Putapesi </i>:: Budapest (Hungary) ',
'<i>ma tomo Sakata </i>:: Jakarta (Indonesia) ',
'<i>ma tomo Sanpansiko </i>:: San Francisco (USA) ',
'<i>ma tomo Sawi </i>:: Sackville (Canada) ',
'<i>ma tomo Sene </i>:: Geneva (Switzerland) ',
'<i>ma tomo Sensan </i>:: St. John\'s (Canada) ',
'<i>ma tomo Sesija </i>:: Shediac (Canada) ',
'<i>ma tomo Sije </i>:: Dieppe (Canada) ',
'<i>ma tomo Solu </i>:: Seoul (South Korea) ',
'<i>ma tomo Tanpele </i>:: Tampere (Finland) ',
'<i>ma tomo Telawi </i>:: Tel Aviv (Israel) ',
'<i>ma tomo Tokijo </i>:: Tokyo (Japan)  ',
'<i>ma tomo Towano </i>:: Toronto (Canada) ',
'<i>ma tomo </i>:: town ',
'<i>ma tomo Tuku </i>:: Turku (Finland) ',
'<i>ma tomo Wankuwa </i>:: Vancouver (Canada) ',
'<i>ma tomo Wenesija </i>:: Venice (Italy) ',
'<i>ma Tona </i>:: Tonga, Tongan ',
'<i>ma Tosi </i>:: Germany, German ',
'<i>ma Tuki </i>:: Turkey, Turkish ',
'<i>ma Tunisi </i>:: Tunisia ',
'<i>ma Tuwalu </i>:: Tuvalu ',
'<i>ma Ukanta </i>:: Uganda ',
'<i>ma Ukawina </i>:: Ukraine, Ukrainian ',
'<i>ma Ulukawi </i>:: Uruguay ',
'<i>ma Uman </i>:: Oman ',
'<i>ma Utun </i>:: Jordan',
'<i>ma Wanuwatu </i>:: Vanuatu ',
'<i>ma Wasikano </i>:: Vatican ',
'<i>ma Wensa </i>:: Sweden',
'<i>meli en mije </i>:: woman and man',
'<i>meli insa </i>:: person who identifies as female, such as a male-to-female transsexual person ',
'<i>meli Italija </i>:: Italian woman ',
'<i>meli lili </i>:: daughter ',
'<i>meli li lon sewi mije </i>:: woman on top ',
'<i>meli li nasa e mije </i>:: Women will drive men crazy',
'<i>meli mije </i>:: masculine girl, butch, tomboy ',
'<i>meli mi pi nanpa wan li nasa </i>:: My first girlfriend was crazy',
'<i>meli </i>:: [n] woman, female, girl, wife, girlfriend  [mod] female, feminine, womanly ',
'<i>meli olin </i>:: wife, girlfriend ',
'<i>meli sama </i>:: sister',
'<i>meli unpa </i>:: female sexual partner',
'<i>mi anpa e jan utala </i>:: I defeated the warrior',
'<i>mi awen weka e ike tan ona </i>:: I keep evil away from her',
'<i>mi en meli mi li wan </i>:: My girlfriend and I got married',
'<i>mi en sina li jan pona </i>:: You and I are friends',
'<i>mi jan li suli </i>:: I am somebody and am important',
'<i>mi jan Pepe </i>:: I am Pepe',
'<i>mi jan pi toki pona </i>:: I am a Toki Ponan',
'<i>mije Epanja </i>:: Spanish man',
'<i>mije insa </i>:: person who identifies as male, such as female-to-male transsexual person ',
'<i>mije lili en meli lili li kipisi sama e linja ona </i>:: The boy and the girl cut each other\'s hair',
'<i>mije lili </i>:: son',
'<i>mije li lon sewi meli </i>:: missionary position ',
'<i>mije li moli la ona li toki wawa e "a!" </i>:: When the man died, he screamed "aaarg!"',
'<i>mije meli </i>:: feminine guy ',
'<i>mije </i>:: [n] man, male, husband, boyfriend  [mod] male, masculine, manly ',
'<i>mije (olin) </i>:: husband, boyfriend ',
'<i>mije sama </i>:: brother ',
'<i>mije unpa </i>:: male sexual partner ',
'<i>mije wan la nimi wan. meli wan la nimi awen </i>:: One man one word, one woman one dictionary',
'<i>mi jo e ilo </i>:: I have a tool',
'<i>mi jo e kili </i>:: I have a fruit',
'<i>mi jo e tomo tawa tu </i>:: I own two cars',
'<i>mi kalama kepeken ilo </i>:: I make sound using an instrument',
'<i>mi kama e pakala </i>:: I caused an accident',
'<i>mi kama jo e telo </i>:: I got the water',
'<i>mi kama lon ni kepeken nasin seme? </i>:: How did I get up here?!',
'<i>mi kama sona </i>:: I\'m learning',
'<i>mi kama tan ma Elopa </i>:: I come from Europe',
'<i>mi kama tan ma Mewika </i>:: I come from America',
'<i>mi kama tan ma tomo Pelin </i>:: I\'m from Berlin',
'<i>mi ken ala ken pilin e monsi sina? </i>:: May I touch your butt? ',
'<i>mi ken ala kute e toki sina </i>:: I can\'t hear what you\'re saying',
'<i>mi ken ala lape </i>:: I can\'t sleep',
'<i>mi ken ala. mi kin moku </i>:: I can\'t, I\'m still eating',
'<i>mi kepeken e ilo </i>:: I\'m using tools',
'<i>mi kepeken e poki e ilo moku </i>:: I\'m using a bowl and a spoon',
'<i>mi kepeken e poki ni </i>:: I\'m using that cup',
'<i>mi kin lukin e ona </i>:: I see it indeed',
'<i>mi kin olin e sina </i>:: I still love you; I love you too',
'<i>mi kin wile tawa tomo mi </i>:: I still want to go to my house',
'<i>mi kule e lipu </i>:: I\'m coloring the paper',
'<i>mi kute e kalama musi </i>:: I\'m listening to music',
'<i>mi kute e toki sina </i>:: I hear your talking',
'<i>mi lape ala </i>:: I\'m not sleeping',
'<i>mi lape la ali li pona </i>:: When I\'m asleep, everything is good',
'<i>mi lape. mi sona </i>:: I sleep, I know',
'<i>mi lawa pona e jan </i>:: I lead people well',
'<i>mi lon e sina </i>:: I made you aware of reality, I forced you to be to present and alert',
'<i>mi lon ma kasi </i>:: I\'m in the forest',
'<i>mi lon tan seme?  </i>:: Why am I here?  ',
'<i>mi lon tomo </i>:: I\'m in the house',
'<i>mi lon </i>:: Yes, I do',
'<i>mi lukin ala e poki laso </i>:: I don\'t see the blue bag',
'<i>mi lukin e ma lon poka pi jan pona mi </i>:: I look at the land with my friend',
'<i>mi lukin e ma. ni li pona tawa mi </i>:: I\'m watching the countryside; this is good to me',
'<i>mi lukin e ma poka jan pona mi </i>:: I look at the land with my friend',
'<i>mi lukin e ni </i>:: I am looking at that',
'<i>mi lukin e soweli luka </i>:: I saw five mammals ',
'<i>mi lukin e waso tu wan </i>:: I saw three birds',
'<i>mi lukin kepeken ilo suno </i>:: I look using a flashlight',
'<i>mi lukin sewi e tomo suli </i>:: I am looking up at the big building',
'<i>mi lukin taso e meli ni! ali li pona </i>:: I only looked at that girl! Everything\'s okay',
'<i>mi meli mi olin e meli </i>:: I am a lesbian ',
'<i>mi mije mi olin e mije </i>:: I am gay',
'<i>mi moku e kili e telo </i>:: I eat fruit and drink water',
'<i>mi moku e kili </i>:: I eat fruit',
'<i>mi moku </i>:: I eat; I am food',
'<i>mi moku </i>:: I\'m eating',
'<i>mi moku kepeken ilo moku </i>:: I eat using an eating utensil',
'<i>mi moku lili e kili lili </i>:: I nibble the small fruit',
'<i>mi moku li pakala </i>:: I eat and destroy',
'<i>mi moku lon poka pi jan pona mi </i>:: I ate with my friend',
'<i>mi moku lon tomo </i>:: I eat in the house',
'<i>mi moku mute. sina moku lili </i>:: I eat more than you',
'<i>mi moku poka jan pona mi </i>:: I ate beside my friend',
'<i>mi moku tan ni: mi wile moku </i>:: I eat because I\'m hungry',
'<i>mi musi ala </i>:: I\'m not having fun; I\'m bored',
'<i>mi musi taso </i>:: I\'m just joking',
'<i>mi mute li lukin lili e ona </i>:: We barely saw it',
'<i>mi mute li moku e telo nasa mute </i>:: We drank a lot of vodka',
'<i>mi mute li pana e moku tawa ona mute </i>:: We gave them food',
'<i>mi mute o moku e kala </i>:: Let\'s eat fish',
'<i>mi mute o musi </i>:: Let\'s have fun',
'<i>mi mute o tawa </i>:: Let\'s go',
'<i>mi mute </i>:: we, us',
'<i>mi </i>:: [n] I, we, me  [mod] mine, ours',
'<i>mi olin e sina </i>:: I love you',
'<i>mi pali mute la mi pilin ike </i>:: When I work a lot, I feel bad',
'<i>mi pali taso </i>:: I just work; all I ever do is work  ',
'<i>mi pana e ko jaki </i>:: I crapped',
'<i>mi pana e sona pi toki pona tawa ona </i>:: I teach her toki pona',
'<i>mi pana e telo jelo </i>:: I peed',
'<i>mi pana sona </i>:: i\'m teaching',
'<i>mi pilin e ni: ona li jo ala e mani </i>:: I think that he doesn\'t have money',
'<i>mi pilin e ni: sina ike </i>:: I think this: You\'re bad',
'<i>mi pilin e seli sijelo sina </i>:: I feel your bodily warmth',
'<i>mi pilin ijo </i>:: I\'m thinking about something; I\'m thinking something',
'<i>mi pilin ike </i>:: I feel bad; I feel sad',
'<i>mi pilin lete </i>:: I\'m cold',
'<i>mi pilin pi meli ni </i>:: I\'m thinking about that woman',
'<i>mi pilin pona </i>:: I feel good; I feel happy',
'<i>mi pini e lape sina </i>:: I ended your sleep; I woke you up',
'<i>mi pona ala pona tawa sina? </i>:: Do you like me?  ',
'<i>mi pona e ale mi, la mi pona e mi </i>:: When I improve all areas of my life, I am making myself good',
'<i>mi pona e ijo </i>:: I\'m fixing something',
'<i>mi pona e ilo suno kepeken ilo lili </i>:: I fixed the flashlight using a small tool',
'<i>mi pona e tomo tawa jan pakala </i>:: I fixed the house for the disabled man',
'<i>mi pona </i>:: I am good',
'<i>mi pona tan ni: mi lon </i>:: I\'m okay because I\'m alive',
'<i>mi pona tan ni: mi sona e sina </i>:: Pleased to meet you',
'<i>mi pona. taso meli mi li pakala </i>:: I\'m okay, but my girlfriend is injured',
'<i>mi sona ala e nimi pi ona mute </i>:: I don\'t know their names',
'<i>mi sona ala e tan </i>:: I don\'t know the reason; I don\'t know why',
'<i>mi sona e ni taso </i>:: I know only that; that\'s all I know',
'<i>mi suli </i>:: I\'m important; I\'m fat',
'<i>mi suli mute. sina suli lili </i>:: I\'m bigger than you',
'<i>mi taso li lon </i>:: I\'m alone',
'<i>mi tawa! </i>:: Bye!  ',
'<i>mi tawa e kiwen </i>:: I\'m moving the rock',
'<i>mi tawa </i>:: I\'m going; bye!',
'<i>mi tawa </i>:: I\'m leaving, goodbye! Said by person leaving (see: tawa pona)',
'<i>mi tawa ma Elopa </i>:: I went to Europe',
'<i>mi tawa supa lape </i>:: I\'m going to bed',
'<i>mi tawa tomo mi </i>:: I\'m going to my house',
'<i>mi tawa tomo toki. ona li pona tawa mi </i>:: I like going to the chat room',
'<i>mi telo e len </i>:: I\'m washing the clothes',
'<i>mi telo e mi lon tomo telo </i>:: I bathe myself in the restroom',
'<i>mi toki jan </i>:: I talked about people ',
'<i>mi toki pi jan ike </i>:: I talked about bad people',
'<i>mi toki tawa sina </i>:: I talk to you',
'<i>mi utala ike </i>:: I fight badly',
'<i>mi wawa ala </i>:: I\'m not strong; I\'m weak',
'<i>mi weka e ijo tu ni </i>:: I got rid of those two things',
'<i>mi weka e ike jan la mi weka e ike mi </i>:: When I forgive somebody\'s wrongdoings, I cleanse myself of negativity',
'<i>mi weka </i>:: I was away',
'<i>mi wile ala e ijo. mi lukin taso </i>:: I don\'t want anything, I\'m just looking',
'<i>mi wile ala pali </i>:: I\'m lazy',
'<i>mi wile ala tawa musi </i>:: I don\'t want to dance',
'<i>mi wile ala toki pi kalama musi </i>:: I don\'t want to talk about music',
'<i>mi wile ala toki tawa sina </i>:: I don\'t want to talk to you',
'<i>mi wile e ilo moku </i>:: I need a fork',
'<i>mi wile e jan soweli lon insa pan </i>:: I want a hamburger',
'<i>mi wile e moku e telo </i>:: I want food and water',
'<i>mi wile e ni: mi lon tomo </i>:: I want this: I\'m at home',
'<i>mi wile e sitelen ma </i>:: I want the map',
'<i>mi wile e soweli lili </i>:: I want a puppy',
'<i>mi wile e suwi! </i>:: I want a cookie! ',
'<i>mi wile e suwi sin! </i>:: I want another cookie! ',
'<i>mi wile kama sona e toki Inli </i>:: I want to learn English',
'<i>mi wile lon tomo </i>:: I want to be at home; I want in a house',
'<i>mi wile lukin e ma ante </i>:: I want to see other countries',
'<i>mi wile lukin e ma e suno </i>:: I want to see the land and the sun',
'<i>mi wile lukin e ma </i>:: I want to see the countryside',
'<i>mi wile lukin e tomo mi. taso mi lon ma ante </i>:: I want to see my house, but I\'m in a different country',
'<i>mi wile moku e kili loje </i>:: I want to eat a red fruit',
'<i>mi wile moku e waso </i>:: I want to eat chicken',
'<i>mi wile moku. taso mi jo ala e moku </i>:: I want to eat, but I don\'t have food',
'<i>mi wile pakala e sina </i>:: I must destroy you',
'<i>mi wile pali kepeken nimi "lon" </i>:: I need more practice with the word "lon"',
'<i>mi wile pana e ko jaki </i>:: I need to crap',
'<i>mi wile pana e telo jelo </i>:: I need to pee',
'<i>mi wile sin e telo pi lape ala </i>:: I need more coffee',
'<i>mi wile tawa ma Oselija </i>:: I want to go to Australia',
'<i>mi wile tawa ma Tosi </i>:: I want to go to Germany',
'<i>mi wile tawa. taso mi ken ala   </i>:: I want to go, but I can\'t',
'<i>mi wile tawa tomo ona kepeken tomo tawa mi </i>:: I want to go to his house using my car',
'<i>mi wile tawa weka </i>:: I want to leave',
'<i>mi wile toki meli </i>:: I want to talk about girls',
'<i>mi wile unpa e ona </i>:: I want to have sex with him/her',
'<i>mi wile unpa e sina </i>:: I want to have sex with you ',
'<i>moku e telo nasa </i>:: to drink alcohol ',
'<i>moku e telo </i>:: to drink ',
'<i>moku kala </i>:: food of fish, fish food; bait',
'<i>moku lili </i>:: pill, snack, small ingestible item ',
'<i>moku lili pi pilin pona mute </i>:: strong euphoric drug taken orally, such as MDMA ',
'<i>moku li lon insa mi </i>:: Food is in my stomach',
'<i>moku li pona tawa ona </i>:: He loves to eat',
'<i>moku li pona </i>:: The food is good',
'<i>moku mi </i>:: my food',
'<i>moku </i>:: [n] food, meal  [v] eat, drink, swallow, ingest, consume  ',
'<i>moku pi soweli moli </i>:: meat',
'<i>moku pi wawa mute </i>:: fat food',
'<i>moku pona! </i>:: Good food! Enjoy your meal! ',
'<i>moku suwi </i>:: sweets, candy, chocolate ',
'<i>moku telo </i>:: liquid food, such as soup',
'<i>moku tomo </i>:: food done at home',
'<i>moku walo </i>:: whiteish food such as rice or plain yogurt',
'<i>moli </i>:: [n] death  [mod] dead, deadly, fatal  [v] to kill, to die, to murder',
'<i>monsi kala </i>:: fish butt, fish tail',
'<i>monsi </i>:: [n] back, ass, rear end, butt, behind  [mod] back, rear ',
'<i>monsuta </i>:: [n] creature that preys on humans, predator, real or imaginary threat, a danger, a source of fear  [mod] to be scary, to be a predator',
'<i>mu </i>:: [interj] woof! meow! moo!',
'<i>mun lili tawa </i>:: asteroid',
'<i>mun li pimeja ale </i>:: it\'s new moon ',
'<i>mun li pimeja e suno </i>:: solar eclipse ',
'<i>mun li sike ale </i>:: it\'s full moon ',
'<i>mun </i>:: [n]moon  [mod]lunar  ',
'<i>musi </i>:: [n] fun, playing, game, recreation, art, entertainment  [mod] artful, fun, recreational  [v] play, have fun, entertain',
'<i>musi pona! </i>:: Good fun! Have fun! ',
'<i>musi pona </i>:: have a nice day, enjoy',
'<i>mute </i>::  [n] amount, quantity  [mod] many, several, very, much, a lot, abundant, numerous, more  [v] make many or much  ',
'<i>mute seme? </i>:: how much?',
'<i>namako </i>:: [n] food additive, salt, accessory, something extra, season  [v] to excite, to stimulate',
'<i>nanpa lili </i>:: few',
'<i>nanpa </i>:: [n] number, ordinal number (first, second, third, and so on)',
'<i>nanpa pi ilo toki </i>:: phone number ',
'<i>nanpa pi ma tomo </i>:: zip code ',
'<i>nanpa pipi </i>:: computer bug',
'<i>nasa la </i>:: foolishly',
'<i>nasa lukin </i>:: funny-looking ',
'<i>nasa </i>:: [mod] silly, crazy, foolish, drunk, strange, stupid, weird  [v] drive crazy, make weird ',
'<i>nasa pona </i>:: cheers, good health!',
'<i>nasin ale </i>:: The Way of Life ',
'<i>nasin ante li pona tawa jan ante </i>:: Different ways are good for different people',
'<i>nasin li jo e telo kiwen </i>:: the roads are icy ',
'<i>nasin mani li ike </i>:: Capitalism is negative',
'<i>nasin </i>:: [n] way, manner, custom, road, path, doctrine, system, method ',
'<i>nasin pi suno kama </i>:: east',
'<i>nasin pi suno tawa </i>:: west',
'<i>nasin pi toki pona </i>:: the ideology behind Toki Pona ',
'<i>nasin pona Juju </i>:: Unitarian Universalism  ',
'<i>nasin pona Latapali </i>:: Rastafarianism',
'<i>nasin pona li mute </i>:: The good ways are man; there are many right ways of doing things ',
'<i>nasin pona </i>:: Taoism, simple or good path',
'<i>nasin sewi Jawatu </i>:: Judaism ',
'<i>nasin sewi Kolisu </i>:: Christianity ',
'<i>nasin sewi ma </i>:: any earth religion, such as Native American beliefs ',
'<i>nasin sewi Puta </i>:: Buddhism ',
'<i>nasin sewi </i>:: religion, spiritual path ',
'<i>nasin sewi Silami </i>:: Islam ',
'<i>nasin tan </i>:: original, unmodified, the first version ',
'<i>nena kon </i>:: nose',
'<i>nena kute </i>:: ear ',
'<i>nena lawa </i>:: nose',
'<i>nena lili pi nena mama </i>:: nipples ',
'<i>nena lili unpa meli </i>:: clitoris ',
'<i>nena mama, nena meli  </i>:: breasts ',
'<i>nena meli </i>:: breasts ',
'<i>nena </i>:: [n] bump, hill, mountain, button, nose ',
'<i>nena sike meli </i>:: female breasts, tits',
'<i>nena suli li pana e ko seli </i>:: a volcano is erupting ',
'<i>ni ante </i>:: there (not here)',
'<i>ni li ike tawa mi </i>:: That is bad to me;  I don\'t like that ',
'<i>ni li jan lili ona pi nanpa tu </i>:: This is her second child ',
'<i>ni li jan seme? </i>:: Who is that? ',
'<i>ni li kule seme? </i>:: What color is that? ',
'<i>ni li musi ala musi? musi </i>:: Is that funny? Yes',
'<i>ni li pilin lete mute </i>:: This is very cold',
'<i>ni li pilin seli lili </i>:: This feels warm',
'<i>ni li pona tawa mi </i>:: That is good to me;  I like that',
'<i>ni li sewi sewi pi ma ale ni </i>:: As the sun rises, you can almost see forever',
'<i>ni li suwi ala suwi? </i>:: Is that sweet?',
'<i>ni li tawa jan pona mi </i>:: This is for my friend',
'<i>nimi kepeken @ </i>:: email',
'<i>nimi "lon" li pona ala tawa mi </i>:: "lon" is not easy for me',
'<i>nimi mi li Ken </i>:: My name is Ken',
'<i>nimi </i>:: [n] word, name',
'<i>nimi pi mi mute </i>:: our names ',
'<i>ni </i>:: this, that, that one',
'<i>noka </i>:: foot, leg ',
'<i>noka kala </i>:: fish legs; fish tail',
'<i>noka kasi </i>:: roots of a tree',
'<i>noka </i>:: [n] leg, foot',
'<i>o awen </i>:: Wait',
'<i>o jo e sijelo pona </i>:: to your health ',
'<i>o kalama ala! </i>:: Don\'t make noise! ',
'<i>o kalama ala </i>:: shut up!',
'<i>oko mi li lukin pona </i>:: my eyes see well ',
'<i>oko </i>:: [n] eye ',
'<i>oko sina li pona lukin </i>:: You have beautiful eyes ',
'<i>olin e jan mute </i>:: to be polyamorous ',
'<i>olin e meli e mije </i>:: to love women and men ',
'<i>olin e meli </i>:: to love women ',
'<i>olin e mije </i>:: to love men ',
'<i>olin </i>:: [n] love  [mod] love  [v] to love (a person) ',
'<i>olin suli li awen </i>:: Old love never rusts',
'<i>o lukin e ni </i>:: Watch this',
'<i>o lukin e pipi loje ni </i>:: Look at that red bug',
'<i>o lukin! meli ni li jo ala e len! </i>:: Look! A naked woman!',
'<i>o moli e pipi kepeken palisa </i>:: Kill the roach with the stick',
'<i>ona anu jan ante li ike? </i>:: Is he bad, or is it the other person who\'s bad? ',
'<i>ona li ike </i>:: He is bad, I don\'t like him ',
'<i>ona li jan pona pi kalama musi </i>:: He is a good musician',
'<i>ona li jo e monsi pona mute </i>:: She has a very nice butt',
'<i>ona li jo e seme? </i>:: What does he have? ',
'<i>ona li kama ante mute </i>:: she changed a lot',
'<i>ona li kama tawa ma mi </i>:: He\'s coming to my country ',
'<i>ona li kama tawa tomo mi </i>:: He came to my house',
'<i>ona li kule e tomo tawa </i>:: He\'s painting the car',
'<i>ona li lawa e jan tawa ma pona </i>:: He led people to the good land ',
'<i>ona li lon ala lon tomo? </i>:: Is he in the house? ',
'<i>ona li lon sewi mi </i>:: He is above me',
'<i>ona li lukin e pipi </i>:: He\'s watching the bug ',
'<i>ona li lukin sama pipi </i>:: He looks like a bug ',
'<i>ona li moku e kili </i>:: She\'s eating fruit',
'<i>ona li pali e ni kepeken nasin seme? </i>:: How did she make that?  ',
'<i>ona li pona e ilo </i>:: She\'s fixing the machine ',
'<i>ona li pona </i>:: It is good, I like it',
'<i>ona li pona li lili </i>:: It is good and is small',
'<i>ona li seme? </i>:: what are they like? ',
'<i>ona li tawa ala tawa ma ike? </i>:: Did he go to the evil land? ',
'<i>ona li tawa ala telo </i>:: He didn\'t go to the lake',
'<i>ona li tawa e len mi </i>:: She moved my clothes',
'<i>ona li tawa sewi kiwen </i>:: She\'s going up the rock ',
'<i>ona li utala kepeken noka insa </i>:: he attacked using the knee',
'<i>ona li wile ala kute e ni </i>:: He shouldn\'t hear this',
'<i>ona li wile jo e ilo </i>:: He would like to have a tool ',
'<i>ona li wile mute e ni </i>:: He wants that a lot',
'<i>ona li wile pakala e pipi </i>:: He wants to squish the spider',
'<i>ona meli li toki e ni tawa mi: sina li lon ala la lon mi li jo e namako ala </i>:: She told me that without me this life had nothing of interest for her',
'<i>ona meli li toki e ni tawa mi: sina li lon ala la lon mi li jo e namako ala </i>:: She told me that without me this life had nothing of interest for her',
'<i>ona mute li nasa e jan suli </i>:: They drove the adults crazy',
'<i>ona mute li tawa utala </i>:: They\'re going to the war',
'<i>ona mute li  utala toki </i>:: They are arguing',
'<i>ona mute </i>:: they, them',
'<i>ona </i>:: [n] he, she, it, they  [mod] his, her, its, their ',
'<i>o olin e jan poka </i>:: Love thy neighbour',
'<i>o open e lupa </i>:: Open the door',
'<i>o pali! </i>:: work!',
'<i>o pana e moku e mani! </i>:: Give me the food and money!',
'<i>o pana e pona tawa ma </i>:: Love the earth; take care of our planet   ',
'<i>o pana e sike tawa mi </i>:: Give the ball to me',
'<i>o pana e sitelen ma tawa mi </i>:: Give me the map ',
'<i>o pana e suwi tawa mi! </i>:: Give me a lollipop!  ',
'<i>open </i>:: [n] the beginning, the start  [mod] beginning  [v]to open, to begin, to start, to turn on ',
'<i>open pi tenpo esun </i>:: monday, first day of week',
'<i>o pilin e nena </i>:: Touch the button',
'<i>o pilin e uta mi kepeken uta sina </i>:: Kiss me',
'<i>o pona </i>:: good luck!',
'<i>o </i>:: [sep] inserted before a command statement, or used after a name to address someone   [interj] Used when calling somebody\'s attention',
'<i>o sina! </i>::',
'<i>o sitelen e ni </i>:: Please, write it down',
'<i>o sona ala. o pali </i>:: Stop thinking, do stuff',
'<i>o sona e sina! </i>:: Know thyself!  ',
'<i>o tawa! </i>:: Go!',
'<i>o tawa ma tomo poka jan pona sina </i>:: Go to the city with your friend',
'<i>o tawa musi poka mi!  </i>:: Dance with me! ',
'<i>o tawa tomo sina! </i>:: Go to your house! ',
'<i>o toki e ni sin </i>:: Please, say that again',
'<i>o toki kepeken tenpo mute </i>:: Please speak more slowly',
'<i>o tu </i>:: Break up; split apart',
'<i>o tu e palisa ni </i>:: Split this stick ',
'<i>o wan! </i>:: Unite!  ',
'<i>o weka e ike mi </i>:: Excuse me, Sorry',
'<i>o weka e jan lili tan ni </i>:: Remove the kid from here  ',
'<i>o weka e len sina </i>:: Remove your clothes',
'<i>pakala kepeken seli </i>:: to burn',
'<i>pakala </i>:: [n] blunder, accident, mistake, destruction, damage, a break or fault  [v] screw up, fuck up, botch, ruin, break, hurt, injure, damage, bungle, spoil, ruin, fall apart   [interj] used as a swear word',
'<i>pali ala </i>:: not working, lazy',
'<i>pali e ike tawa </i>:: to do bad things to, to show disrespect for ',
'<i>pali li ike tawa mi </i>:: I\'m lazy ',
'<i>pali li pana e sona </i>:: One learns by experience',
'<i>pali li pana e sona </i>:: Work gives you experience',
'<i>pali mute a! </i>:: What a lot of work!',
'<i>pali </i>:: [n] activity, work, deed, project  [mod] active, work-related, operating, working  [v] do, make, build, create',
'<i>pali pona li lawa tawa lon </i>:: good work is most importand in life; order is the half of life',
'<i>pali pona </i>:: order, good work',
'<i>palisa li lawa e mije </i>:: A man\'s penis controls him',
'<i>palisa lili noka </i>:: toes',
'<i>palisa luka </i>:: finger',
'<i>palisa mije </i>:: penis',
'<i>palisa moli </i>:: cigarette',
'<i>palisa </i>:: [n] long, mostly hard object; penis-shaped thing, dildo; rod; stick; pointy thing; tree branch',
'<i>palisa sina li kiwen </i>:: Your cock is hard',
'<i>palisa tawa </i>:: vibrating dildo',
'<i>palisa uta </i>:: tongue ',
'<i>pali sin </i>:: retry',
'<i>pana e ko jaki </i>:: to pooh, to shit ',
'<i>pana e kon pi pilin pona </i>:: to laugh ',
'<i>pana e moku tan uta </i>:: vomit',
'<i>pana e moku tawa </i>:: to feed, nourish ',
'<i>pana e palisa lon lupa </i>:: to penetrate ',
'<i>pana e palisa uta lon </i>:: to lick ',
'<i>pana e pilin pona tawa </i>:: to send positivity to, make feel good ',
'<i>pana e sona </i>:: to teach; to give knowledge',
'<i>pana e supa sewi </i>:: give a roof to protect from rain',
'<i>pana e telo jelo </i>:: to pee, to urinate ',
'<i>pana e telo oko </i>:: to cry, weep ',
'<i>pana e telo walo mije </i>:: to ejaculate',
'<i>pana e uta lon lupa meli </i>:: to perform cunnilingus ',
'<i>pana e uta lon palisa </i>:: to fellate ',
'<i>pana e uta tawa ona </i>:: to kiss ',
'<i>pana lon esun </i>:: to give at the market, trade, sell',
'<i>pana </i>:: [v] give, put, send, place, release, emit, cause  [n] giving, transfer, exchange ',
'<i>pana wawa </i>:: BDSM',
'<i>pan </i>:: [n] bread, cereals, pasta, rice',
'<i>pan suwi </i>:: sweet cookie, sugar cookie',
'<i>pilin ala </i>:: indifferent, unfeeling ',
'<i>pilin e ike jan </i>:: to pity somebody, feel bad for somebody ',
'<i>pilin e moli jan </i>:: to mourn somebody ',
'<i>pilin e weka jan </i>:: to miss somebody ',
'<i>pilin ike tan </i>:: be afraid of, sad because of, regret, be offended by ',
'<i>pilin ike tawa </i>:: to have negative feelings for, be upset at, angry at, hate, resent ',
'<i>pilin ike </i>:: to feel bad, sad, depressed, unhappy, bitter, discontented, grumpy ',
'<i>pilin ike wawa </i>:: to have intense negative feelings, be pissed off, furious ',
'<i>pilin kepeken e nena lawa </i>:: smell',
'<i>pilin nasa </i>:: drunk, high, to feel silly, strange, weird, crazy, drunk, high  ',
'<i>pilin </i>:: [n] feelings, emotion, heart  [v] feel, think, sense, touch ',
'<i>pilin pona li pana e sijelo pona </i>:: Positive feelings grant good health; mind over matter   ',
'<i>pilin pona mute </i>:: to feel great, amazing, awesome ',
'<i>pilin pona tan </i>:: to feel good because of, to enjoy ',
'<i>pilin pona </i>:: to feel good, happy, content, enjoy oneself, comfortable ',
'<i>pilin wawa </i>:: to feel strong, energetic, excited, confident, proud',
'<i>pilin wawa unpa </i>:: orgasm ',
'<i>pimeja laso </i>:: blueish black ',
'<i>pimeja li lon </i>:: it is night ',
'<i>pimeja li tawa insa kon mi </i>:: Darkness fills my soul',
'<i>pimeja </i>:: [mod] black, dark  [n] darkness, shadows  [v] darken ',
'<i>pini li pona la ale li pona </i>:: Is the end good -- everything is good',
'<i>pini </i>:: [n] end, tip  [mod] completed, finished, past, done, ago  [v] finish, close, end, turn off  ',
'<i>pini palisa </i>:: glans, head of the penis ',
'<i>pini pi nena mama </i>:: nipples ',
'<i>pini pi sike suno </i>:: end  of the year',
'<i>pini pi wan musi </i>:: end level',
'<i>pipi </i>:: bug, of bug  ',
'<i>pipi li lon ala lon poka mi? </i>:: Is a bug beside me?',
'<i>pipi li lon anpa mi </i>:: The bug is underneath me',
'<i>pipi li lukin li unpa </i>:: The bug looks and has sex',
'<i>pipi li moku ala moku e kili? </i>:: Are the bugs eating the fruit? ',
'<i>pipi li moku e kasi </i>:: Bugs eat plants',
'<i>pipi li moku e mi </i>:: The mosquito bit me',
'<i>pipi li moli </i>:: The bug is dead',
'<i>pipi li wile moku e telo </i>:: The bug is thirsty',
'<i>pipi </i>:: n bug, insect, spider ',
'<i>pipi seme li pakala e sina? </i>:: Which bug hurt you?  ',
'<i>pi </i>:: [sep] essentially means "of" ',
'<i>pi </i>:: sep of, belonging to ',
'<i>poka mi li pakala </i>:: My hip hurts',
'<i>poka </i>:: n side, hip, next to   mod neighboring   prep in the accompaniment of, with ',
'<i>poka </i>:: side, hip, close to, nearby ',
'<i>poka telo </i>:: water side, the beach',
'<i>poki kon </i>:: lungs',
'<i>poki lete </i>:: fridge, refrigerator ',
'<i>poki </i>:: [n] container, box, bowl, cup',
'<i>poki ni li lon jaki </i>:: That bottle is in the dirt',
'<i>poki seli </i>:: oven, microwave ',
'<i>poki sike </i>:: glass',
'<i>poki telo </i>:: sink, bathtub, bottle, glass',
'<i>poki walo </i>:: egg',
'<i>pona e pilin jan </i>:: cheer up, make somebody happy ',
'<i>pona la </i>:: fortunately',
'<i>pona lukin </i>:: pretty, attractive, beautiful, pretty, handsome ',
'<i>pona! mi kin tawa ma Elopa </i>:: Cool! I also went to Europe',
'<i>pona moku </i>:: delicious, tasty ',
'<i>pona </i>:: [n] good, simplicity, positivity  [mod] good, simple, positive, nice, correct, right  [interj] great! good! thanks! OK! cool! yay! ',
'<i>pona unpa </i>:: sexy, good in bed',
'<i>pu lili </i>:: small book, novellette',
'<i>pu </i>:: [n] book, tokipona nirvana (jan Sonja), maybe usable as comma (punctuation)',
'<i>pu ni li toki e ni: jan utala pona li moli e akesi monsuta </i>:: This book is about a knight who kills a dragon',
'<i>pu pi jan lili </i>:: childrens book',
'<i>pu suli </i>:: large book, novel',
'<i>pu suli </i>:: large book, novel',
'<i>sama la </i>:: similarily',
'<i>sama li ike </i>:: Equality is bad',
'<i>sama </i>:: [mod] same, similar, equal, of equal status or position  [prep] like, as, seem  [cont] similarly, in the same way that',
'<i>seli kon </i>:: smoke',
'<i>seli lili li lon </i>:: It\'s warm',
'<i>seli li lon </i>:: it\'s warm or hot ',
'<i>seli li lon la mi pana e telo tan selo mi </i>:: When it\'s hot, I sweat',
'<i>seli mute li lon </i>:: It\'s very hot',
'<i>seli </i>:: [n] fire, warmth, heat  [mod] hot, warm, cooked  [v] heat, warm up, cook, burn',
'<i>seli pakala </i>:: explossion',
'<i>seli sewi </i>:: lightning',
'<i>seli suno li seli e tomo mi </i>:: The sun\'s warmth heats my home',
'<i>seli suno </i>:: the sun\'s heat ',
'<i>selo lon pini palisa </i>:: foreskin ',
'<i>selo mi li wile e ni: mi pilin e ona </i>:: My skin wants this: I touch it',
'<i>selo </i>:: [n] outside, surface, skin, shell, bark, shape, peel ',
'<i>seme li lon poka mi? </i>:: What is beside me? ',
'<i>seme li lon tomo mi? </i>:: What is in my house? ',
'<i>seme li moku e kili mi? </i>:: What is eating my fruit? ',
'<i>seme li olin? </i>:: what is love?',
'<i>seme li pona tawa sina? </i>:: What do you like?',
'<i>seme li utala e sina? </i>:: What attacked you? ',
'<i>seme </i>:: [question] what, where, which, who, how many, and so on (used to make question sentences) ',
'<i>sewi li laso </i>:: The sky is blue',
'<i>sewi monsi </i>:: upper back, shoulders ',
'<i>sewi </i>:: [n] sky, roof, top [v] high, up, above, top, over, on, sanctify  [mod] superior, elevated, religious, formal, holy',
'<i>sewi pi sinpin lawa </i>:: forehead ',
'<i>sijelo namako </i>:: piercing, tattoo, body art',
'<i>sijelo </i>:: [n] health, body, physical state',
'<i>sike e suno nunpa wan </i>:: first aniversary, when born',
'<i>sike mama waso </i>:: egg ',
'<i>sike mije </i>:: man\'s testicles ',
'<i>sike </i>:: [n] circle, wheel, sphere, ball, cycle  [mod] round, cyclical ',
'<i>sike suno wan </i>:: one year',
'<i>sina jo e kili anu telo nasa? </i>:: Do you have the fruit the wine? ',
'<i>sina kama anu seme? </i>:: Are you coming or what?  ',
'<i>sina kama e ni: mi wile moku </i>:: You caused this: I want to eat; you made me hungry',
'<i>sina kama jo e jan pona lon ni </i>:: You will get friends there',
'<i>sina kama tan ma seme? </i>:: Which country do you come from?',
'<i>sina kama tan seme? </i>:: Why did you come?',
'<i>sina ken ala ken kama?  </i>:: Can you come?',
'<i>sina ken ala ken lape? </i>:: Can you sleep?',
'<i>sina kepeken ala kepeken e ni?  </i>:: Are you using that?',
'<i>sina lon ala lon ma tomo Wankuwa? </i>:: Do you live in Vancouver?',
'<i>sina lon ma tomo seme? </i>:: What city do you live in?',
'<i>sina lon seme? </i>:: Where are you?',
'<i>sina lukin ala lukin e kiwen? </i>:: Do you see the rock?',
'<i>sina lukin ala lukin e sitelen tawa X-Files? </i>:: Do you watch The X-Files?',
'<i>sina lukin e jan seme? </i>:: Whom did you see?',
'<i>sina lukin e pipi </i>:: You\'re watching a bug',
'<i>sina lukin e seme? </i>:: What are you watching? ',
'<i>sina lukin sewi e suno </i>:: You look up at the sun ',
'<i>sina moku e telo nasa la sina nasa </i>:: If you drink beer, you\'ll be silly',
'<i>sina moli la sina ken ala toki </i>:: If you are dead, you can\'t speak',
'<i>sina nimi li seme </i>:: What\'s your name?',
'<i>sina </i>:: [n] you  [mod] your ',
'<i>sina pakala e ilo kepeken nasin seme?  </i>:: How did you break the tool?',
'<i>sina pakala e seme? </i>:: What did you hurt?',
'<i>sina pali e ni kepeken nasin seme? </i>:: How did you make this?',
'<i>sina pana ala pana e moku tawa jan lili? </i>:: Did you give food to the child? ',
'<i>sina pana e ike la sina kama jo e ike </i>:: If you give evil, you will receive evil',
'<i>sina pilin e seme? </i>:: What are you thinking? / What do you think?',
'<i>sina pilin seme? </i>:: how are you? how are you feeling? how do you feel?',
'<i>sina pona ala pona? </i>:: Are you okay? ',
'<i>sina pona </i>:: You are good; you fix',
'<i>sina sona ala sona e toki Inli? </i>:: Do you speak English? ',
'<i>sina sona ala sona e toki mi? </i>:: Do you understand what I\'m saying? ',
'<i>sina sona e toki ni la sina sona e toki pona! </i>:: If you know what this says then you know toki pona!',
'<i>sina suli </i>:: You are tall',
'<i>sina tan ma seme </i>:: Where are you from?',
'<i>sina tawa ma tomo tan seme?  </i>:: Why did you go to the city? ',
'<i>sina tawa poka jan seme? </i>:: Whom did you go with?',
'<i>sina toki e ni tawa mi: sina moku </i>:: You told me that you are eating',
'<i>sina toki pi mama anu jan lili? </i>:: Are you talking about the parent, or is the child that you\'re talking about? ',
'<i>sina toki tawa jan seme? </i>:: Whom are you talking to? ',
'<i>sina toki tawa mi anu ona? </i>:: Are you talking to me, or are you talking to him? ',
'<i>sina toki tawa mi anu seme? </i>:: You ask me? ',
'<i>sina wile ala wile moku? </i>:: Do you want to eat? ',
'<i>sina wile ala wile pali? wile ala </i>:: Do you want to work? No',
'<i>sina wile e mani anu seme? </i>:: Do you want the money or what? ',
'<i>sina wile e moku anu telo? </i>:: Do you want food, or do you want water?',
'<i>sina wile kama anu seme? </i>:: Do you want to come or what?',
'<i>sina wile kama tawa tomo toki </i>:: You should come to the chat room',
'<i>sina wile kepeken e ilo </i>:: You have to use tools',
'<i>sina wile moku anu seme? </i>:: Do you want to eat or what? ',
'<i>sina wile pali e seme? </i>:: What do you want to do?',
'<i>sina wile tawa ma seme? </i>:: What place do you want to go to?',
'<i>sina wile tawa telo suli </i>:: You want to go to the ocean',
'<i>sina wile toki e tan tawa mi </i>:: You have to tell me why',
'<i>sina wile toki tawa mije anu meli?  </i>:: Do you want to talk to a male, or a female? ',
'<i>sin en ante li sin e lawa li pana e sona </i>:: Novelty and change freshen the mind and bring insight',
'<i>sin </i>:: [mod] new, fresh, another, more  [v] renew, renovate, freshen',
'<i>sinpin lawa </i>:: face',
'<i>sinpin </i>:: [n] front, chest, torso, abdomen, face, wall',
'<i>sitelen ma </i>:: map ',
'<i>sitelen </i>:: [n] picture, image  [v] draw, write ',
'<i>sitelen pi ilo nanpa </i>:: computer screen ',
'<i>sitelen tawa "Bowling for Columbine" li kin pona </i>:: The movie "Bowling for Columbine" is also good',
'<i>sitelen tawa "Fahrenheit 9/11" li pona tawa mi </i>:: I like the movie "Fahrenheit 9/11"',
'<i>sitelen tawa </i>:: movie, TV show ',
'<i>sitelen toki </i>:: writing',
'<i>sitelen unpa </i>:: visual erotica, porn',
'<i>sona e toki </i>:: to know, speak, understand a language',
'<i>sona mute </i>:: smart, intelligent, wise',
'<i>sona </i>:: [n] knowledge, wisdom, intelligence, understanding  [v] know, understand, know how to ',
'<i>sona pona e toki </i>:: to master a language',
'<i>sona pona li sona sewi ala. ona li sona mute ale </i>:: real inteligence is not to know things, it is to know a lot of things',
'<i>soweli li kama moli </i>:: The cheetah is dying',
'<i>soweli lili pi ilo nanpa </i>:: computer mouse ',
'<i>soweli li toki e mu </i>:: Cows say moo',
'<i>soweli mi li kama moli </i>:: My dog is dying',
'<i>soweli </i>:: [n] animal, lovable animal, mammal, meat from a mammal such as beef or pork',
'<i>soweli ni li pona moku </i>:: This cow is good to eat',
'<i>suli </i>:: [mod] big, tall, fat, long, adult, important  [v] enlarge, lengthen  [n] size   ',
'<i>suno li jelo </i>:: The sun is yellow',
'<i>suno li lon </i>:: It\'s sunny',
'<i>suno li lon poka pimeja </i>:: Light is beside darkness; opposites are interconnected; yin and yang',
'<i>suno li lon sewi mi </i>:: The sun is above me',
'<i>suno li lon sewi </i>:: The sun is in the sky',
'<i>suno li suli ala suli? </i>:: Is the sun big? ',
'<i>suno li suli </i>:: The sun is big',
'<i>suno </i>:: [n] sun, light [mod] sunny, shiny, of or relating to the sun, daylight',
'<i>suno pona! </i>:: Good sun! Good day!',
'<i>supa lape </i>:: bed',
'<i>supa lawa </i>:: pillow',
'<i>supa li pona </i>:: the floor is clean, good',
'<i>supa moku </i>:: dinner table',
'<i>supa monsi </i>:: chair, couch',
'<i>supa </i>:: [n] horizontal surface such as furniture; a table, chair, or pillow; the floor',
'<i>supa pali </i>:: work desk',
'<i>supa pi lupa tomo </i>:: window cristal',
'<i>suwi lukin </i>:: cute',
'<i>suwi </i>:: [n] candy, sweet food, cookie  [mod] sweet, cute  [v] sweeten',
'<i>tan </i>:: [prep] from, by, because of, since  [n] origin, cause, reason',
'<i>taso </i>:: [mod] only, sole  [conj] but',
'<i>tawa kala </i>:: movement of a fish, swim',
'<i>tawa kala </i>:: movement of a fish, swim',
'<i>tawa ma lete tawa soweli walo </i>:: north',
'<i>tawa ma lete tawa waso walo pimeja </i>:: south',
'<i>tawa musi </i>:: resume, dance, perform',
'<i>tawa pona! </i>:: Go well! Good bye! Bon voyage',
'<i>tawa pona </i>:: Leave well, goodbye! Said by person not leaving (see: mi tawa)',
'<i>tawa </i>:: [v] to go to, to move, to, for  [prep] to, in order to, towards, for, until  [n] movement, transportation  [mod] moving, mobile',
'<i>telo e luka </i>:: wash your hands',
'<i>telo e mi </i>:: to shower',
'<i>telo jaki lon nena sinpin </i>:: snot',
'<i>telo jelo </i>:: urine, pee (yellow fluid)',
'<i>telo kili </i>:: juice',
'<i>telo kili ni li suwi </i>:: This fruit drink is sweet',
'<i>telo kiwen </i>:: ice',
'<i>telo kiwen ko </i>:: snow',
'<i>telo kiwen lili li kama </i>:: it\'s hailing',
'<i>telo li kama </i>:: it\'s raining',
'<i>telo lili </i>:: droplet, drops',
'<i>telo lili li lon kon </i>:: it\'s humid',
'<i>telo linja </i>:: river',
'<i>telo li pona </i>:: Water is good (or simple)',
'<i>telo li suli </i>:: The lake is big',
'<i>telo loje </i>:: blood',
'<i>telo (loje) mun </i>:: menses ',
'<i>telo mama soweli </i>:: cow milk',
'<i>telo nasa </i>:: alcohol, such as beer, wine, whisky',
'<i>telo nasa loje seli </i>:: mulled claret (hot wine)',
'<i>telo nasa loje </i>:: wine',
'<i>telo nasa pi wawa ala </i>:: weak beer, US American beer ',
'<i>telo nasa pona! </i>:: generic toast ',
'<i>telo nasa wawa </i>:: vodka, whisky, ',
'<i>telo </i>:: [n] water, liquid, juice, sauce, beverage  [v] water, to wash',
'<i>telo ona </i>:: her water ',
'<i>telo pi lape ala </i>:: coffee ',
'<i>telo seli </i>:: hot beverage, such as coffee or hot cocoa',
'<i>telo seli jelo </i>:: green tea  ',
'<i>telo seli pimeja pi lape ala </i>:: coffee ',
'<i>telo seli wawa </i>:: coffee ',
'<i>telo sijelo loje </i>:: blood or any red bodily fluid',
'<i>telo suli li ike tawa mi </i>:: I don\'t like the ocean',
'<i>telo suli li laso </i>:: The big water [ocean] is blue',
'<i>telo suli </i>:: sea, ocean',
'<i>telo tawa </i>:: to swim, river, flow',
'<i>telo walo mije </i>:: sperm',
'<i>telo wawa </i>:: energy drink  ',
'<i>tenpo ala </i>:: never ',
'<i>tenpo ali </i>:: always, all the time ',
'<i>tenpo ali la o kama sona!  </i>:: Always learn!  ',
'<i>tenpo jelo </i>:: summer - yellow for the sun (see: tenpo seli)',
'<i>tenpo kama la mi lape </i>:: In the future, I\'ll sleep',
'<i>tenpo kama lili </i>:: soon, after',
'<i>tenpo kama </i>:: the future',
'<i>tenpo laso </i>:: spring - blue water, green for plants (see: tenpo seli lili)',
'<i>tenpo lete lili </i>:: autumn (see: tenpo loje)',
'<i>tenpo lete </i>:: winter  (see: tenpo walo)',
'<i>tenpo lili la mi wile weka </i>:: I must leave soon',
'<i>tenpo lili </i>:: soon, moment, briefly  ',
'<i>tenpo li sijelo e sijelo ike ali </i>:: The time heals all wounds',
'<i>tenpo li tawa la sona li kama </i>:: Time comes -- advice comes',
'<i>tenpo loje </i>:: autumn - red for autumn leaves (see: tenpo lete lili)',
'<i>tenpo moku </i>:: mealtime ',
'<i>tenpo mun kama </i>:: next month',
'<i>tenpo mun </i>:: month ',
'<i>tenpo mun ni </i>:: this month ',
'<i>tenpo mun pi nanpa luka luka </i>:: October ',
'<i>tenpo mun pi nanpa luka luka tu </i>:: December ',
'<i>tenpo mun pi nanpa luka luka wan </i>:: November ',
'<i>tenpo mun pi nanpa luka </i>:: May  ',
'<i>tenpo mun pi nanpa luka tu </i>:: July ',
'<i>tenpo mun pi nanpa luka tu tu </i>:: September ',
'<i>tenpo mun pi nanpa luka tu wan </i>:: August ',
'<i>tenpo mun pi nanpa luka wan </i>:: June  ',
'<i>tenpo mun pi nanpa tu </i>:: February ',
'<i>tenpo mun pi nanpa tu tu </i>:: April ',
'<i>tenpo mun pi nanpa tu wan </i>:: March ',
'<i>tenpo mun pi nanpa wan </i>:: January ',
'<i>tenpo mun pini </i>:: last month',
'<i>tenpo mute </i>:: sometimes, usually, often, many times ',
'<i>tenpo ni la mi lon </i>:: At this time, I am here',
'<i>tenpo ni </i>:: now, the present (this time) ',
'<i>tenpo </i>:: [n] time, period of time, moment, duration, situation ',
'<i>tenpo pimeja </i>:: night, dark times',
'<i>tenpo pimeja ni la mun li suli </i>:: The moon is big tonight',
'<i>tenpo pimeja ni </i>:: tonight',
'<i>tenpo pimeja pini la mi kama nasa </i>:: Last night, I became drunk',
'<i>tenpo pimeja pini la mi lukin e sitelen tawa X-Files   </i>:: Last night I watched X-Files',
'<i>tenpo pimeja pini </i>:: last night',
'<i>tenpo pi mute seme la sina sike e suno? </i>:: How old are you? ',
'<i>tenpo pini la mi weka </i>:: In the past, I was away',
'<i>tenpo pini </i>:: the past',
'<i>tenpo pona Kolisu </i>:: Christmas ',
'<i>tenpo pona la mi lon! </i>:: I\'m back, and just in time!',
'<i>tenpo seli lili </i>:: spring (see: tenpo laso)',
'<i>tenpo seli </i>:: summer (see: tenpo jelo)',
'<i>tenpo seme la ona li kama lon tomo sina? </i>:: When is he coming to your house? ',
'<i>tenpo seme </i>:: when',
'<i>tenpo sike </i>:: year ',
'<i>tenpo sin </i>:: again ',
'<i>tenpo sitelen </i>:: calendar, schedule',
'<i>tenpo suli </i>:: long time ',
'<i>tenpo suno </i>:: day',
'<i>tenpo suno kama la mi pali e lipu sin </i>:: I\'ll update my web page tomorrow',
'<i>tenpo suno kama la mi wile pali </i>:: I have to work tomorrow',
'<i>tenpo suno kama </i>:: tomorrow',
'<i>tenpo suno luka tu </i>:: week',
'<i>tenpo suno ni </i>:: today',
'<i>tenpo suno pi nanpa luka </i>:: Friday ',
'<i>tenpo suno pi nanpa luka tu </i>:: Sunday ',
'<i>tenpo suno pi nanpa luka wan </i>:: Saturday ',
'<i>tenpo suno pi nanpa tu </i>:: Tuesday ',
'<i>tenpo suno pi nanpa tu tu </i>:: Thursday ',
'<i>tenpo suno pi nanpa tu wan </i>:: Wednesday ',
'<i>tenpo suno pi nanpa wan </i>:: Monday ',
'<i>tenpo suno pini </i>:: yesterday ',
'<i>tenpo suno pi pali ala </i>:: public holiday ',
'<i>tenpo suno pi pini mute la mi tawa tomo </i>:: I went home a while ago',
'<i>tenpo suno pi sike e suno </i>:: birthday',
'<i>tenpo suno sin ali la sina moku e telo seli pimeja </i>:: Every morning I drink coffee',
'<i>tenpo suno sin </i>:: morning ',
'<i>tenpo telo </i>:: rainy season ',
'<i>tenpo tu tu la mi sike e suno </i>:: I am 4 year old; lit: Four times I circled the sun',
'<i>tenpo walo </i>:: winter - white for snow (see: tenpo lete)',
'<i>toki Alapi </i>:: Arabic ',
'<i>toki ali o </i>:: hello everybody!',
'<i>toki ante </i>:: a dialect of tokipona that adds or changes words to the original language as developed by jan Sonja; this is usually done by conlang fans',
'<i>toki Apikan </i>:: Afrikaans ',
'<i>toki Awasa </i>:: Hausa ',
'<i>toki Epelanto </i>:: Esperanto ',
'<i>toki Ewantalu </i>:: Ewantal ',
'<i>toki! </i>:: Hello!, Hi!',
'<i>toki ike lon </i>:: to say bad things about, complain about ',
'<i>toki ike tawa </i>:: to say bad things to, insult, speak rudely to ',
'<i>toki ike </i>:: to say negative things; a "dialect" specifically characterized by gramatically wrong toki pona',
'<i>toki Inli </i>:: English',
'<i>toki Inli li pona </i>:: The English language is good',
'<i>toki Inli pona </i>:: Basic English',
'<i>toki Insi </i>:: Hindi',
'<i>toki Intelinka </i>:: Interlingua',
'<i>toki Iwisi </i>:: Hebrew',
'<i>toki Jolupa </i>:: Yoruba ',
'<i>toki Kalike </i>:: Scots Gaelic ',
'<i>toki Kanse </i>:: French language ',
'<i>toki Kantun </i>:: Cantonese ',
'<i>toki Kisawili </i>:: Swahili ',
'<i>toki Kuwenja </i>:: Quenya, Elvish ',
'<i>toki li ni </i>:: it says',
'<i>toki li pona </i>:: communication is good',
'<i>toki li pona tawa mi </i>:: I like talking; I like languages',
'<i>toki Lolan </i>:: Loglan         ',
'<i>toki Loma </i>:: Latin ',
'<i>toki lon toki </i>:: to speak in a language ',
'<i>toki Losupan </i>:: Lojban ',
'<i>toki Lunasimi </i>:: Quechua ',
'<i>toki Malasi </i>:: Marathi ',
'<i>toki nanpa wan </i>:: primary language ',
'<i>toki nasa </i>:: a dialect of tokipona more expressive and less philosophical than original dialect developed by jan Sonja',
'<i>toki </i>:: [n] language, speech, story, phrase [interj] hey! [v] to talk, to speak, to comunicate, to say or chat',
'<i>toki Nosiki sin </i>:: Norwegian Nynorsk ',
'<i>toki Olapu </i>:: Volapük ',
'<i>toki Pansapi </i>:: Punjabi ',
'<i>toki Pasiki </i>:: Fyksian ',
'<i>toki Pasuto </i>:: Pashto ',
'<i>toki pona e toki </i>:: to speak a language well ',
'<i>toki pona li pona tawa mi </i>:: I like Toki Pona',
'<i>toki pona li toki pona </i>:: Toki Pona is a good language',
'<i>toki pona lon </i>:: to say good things about, praise  ',
'<i>toki pona pi nasin nanpa </i>:: a "dialect" of tokipona which could be written by computers, would use short sentences, could be verifiably grammatically correct; and could be used by robots; this is the most direct subset of the original dialect developed by jan Sonja',
'<i>toki pona pi nasin tan </i>:: the original tokipona dialect as developed by jan Sonja (for more information on dialects, see: http://www.suburbandestiny.com/?p=799 )',
'<i>toki pona tawa </i>:: to say nice things to, compliment ',
'<i>toki pona </i>:: Toki Pona, to say nice things, the good talking',
'<i>toki Sami </i>:: Laplander ',
'<i>toki Sankitu </i>:: Sanskrit ',
'<i>toki Sinan </i>:: Klingon ',
'<i>toki sitelen </i>:: written language ',
'<i>toki sona </i>:: proverbs ',
'<i>toki suli </i>:: conference talk, discourse',
'<i>toki Tamasiko </i>:: Berber, Tamazight ',
'<i>toki Tami </i>:: Tamil ',
'<i>toki Teluku </i>:: Telugu ',
'<i>toki utala tawa </i>:: to argue with, criticize ',
'<i>toki Utu </i>:: Urdu ',
'<i>tomo lape </i>:: bedroom ',
'<i>tomo mani </i>:: bank ',
'<i>tomo mi li weka tan ni </i>:: My house is away from here',
'<i>tomo mi </i>:: my house ',
'<i>tomo moku </i>:: (place to eat) grocery store, restaurant, dining room, kitchen, grocery store',
'<i>tomo esun </i>:: market (stocks)',
'<i>tomo moku li kama open ala open? </i>:: will the food shop be open or not?',
'<i>tomo moku li open ala open? </i>:: is the food shop open?',
'<i>tomo </i>:: [n] a building or construction such as a house or home  [mod] urban, domestic, household ',
'<i>tomo pali </i>:: work(place), office, factory',
'<i>tomo pi ijo kama jo </i>:: shop',
'<i>tomo pi jan Keli en mije ona li suli </i>:: The house of Keli and her boyfriend is big',
'<i>tomo pi jan Lisa </i>:: Lisa\'s house ',
'<i>tomo pi mi mute li pakala </i>:: Our house is messed up',
'<i>tomo pi ona mute </i>:: their house ',
'<i>tomo pi telo en moku pana </i>:: restaurant ',
'<i>tomo pi telo nasa </i>:: building of alcohol; a bar, pub',
'<i>tomo sona </i>:: school, university ',
'<i>tomo tawa </i>:: car (moving construction) ',
'<i>tomo tawa kon </i>:: airplane, helicopter ',
'<i>tomo tawa linja </i>:: train',
'<i>tomo tawa sina li pakala ala pakala? </i>:: Is your car messed up? ',
'<i>tomo tawa suli </i>:: bus',
'<i>tomo tawa telo </i>:: boat, ship ',
'<i>tomo telo </i>:: bathroom, toilette, water closet, restroom',
'<i>tomo telo li lon seme? </i>:: Where\'s the bathroom?',
'<i>tomo toki </i>:: chat room, conference room ',
'<i>tomo unpa </i>:: sex place, such as a bedroom, boudoir, brothel, sex house, or brothel',
'<i>tu </i>:: [n] 2, duo, pair  [mod] two  [v] double; separate, cut, or divide in two ',
'<i>tu tu </i>:: 2 + 2 = 4 ',
'<i>tu wan </i>:: 2 + 1 = 3 ',
'<i>unpa e palisa meji kepeken uta sinpin </i>:: giving a blowjob',
'<i>unpa li pona </i>:: sex is good, I like sex',
'<i>unpa nasa </i>:: kinky sex ',
'<i>unpa </i>:: [n] sex, sexuality [mod] sexual, erotic  [v] to fuck, to have sex with, sleep with',
'<i>unpa sama soweli </i>:: doggy style ',
'<i>unpa uta </i>:: oral sex, cunnilingus',
'<i>utala li ike </i>:: Conflict is bad',
'<i>utala li ike tawa mi </i>:: I don\'t like wars',
'<i>utala </i>:: [n] conflict, disharmony, competition, fight, war, battle, attack, blow, argument, physical or verbal violence   [v] hit, strike, attack, compete against ',
'<i>uta </i>:: [n] mouth  [mod] oral',
'<i>walo </i>:: [mod] white, light colour  [n] a white thing or part, whiteness, lightness',
'<i>walo pimeja </i>:: grey (dark white) ',
'<i>walo uta </i>:: teeth  ',
'<i>wan </i>:: [mod] one, a  [n] unit, element, particle, part, piece  [v] unite, make one ',
'<i>wan sijelo </i>:: body part ',
'<i>wan taso </i>:: alone',
'<i>waso ike li tawa sike lon lawa mi </i>:: crows fly above my head in circles',
'<i>waso kala </i>:: fishy bird; a bird that swims or dives for food',
'<i>waso li ken ala lukin la ona li kin ken jo e kili </i>:: A blind chicken can find a corn too',
'<i>waso li tawa lon kon </i>:: Birds fly in air',
'<i>waso </i>:: [n] bird, winged animal ',
'<i>wawa kon </i>:: eolic energy',
'<i>wawa li lon insa </i>:: Energy comes from inside; youth is all in the heart',
'<i>wawa </i>:: [n] energy, strength, power  [mod] energetic, strong, fierce, intense, sure, confident  [v] strengthen, energize, empower',
'<i>weka e ike jan </i>:: forgive somebody',
'<i>weka lili li pona tawa lawa </i>:: Temporary isolation is good for meditation',
'<i>weka </i>:: [n] away  [v] to remove, to eliminate, missing, absence, throw away, get rid of  [mod] not present',
'<i>weka sona </i>:: forget',
'<i>wile e pona tawa jan </i>:: to wish somebody well ',
'<i>wile ike </i>:: to have negative intentions, malevolent ',
'<i>wile lape </i>:: to be tired, sleepy, wanting to rest ',
'<i>wile lawa </i>:: to be dominant  ',
'<i>wile moku e telo </i>:: to be thirsty',
'<i>wile moku </i>:: hungry, to be hungry',
'<i>wile moli e jan </i>:: homicidal, wanting to murder',
'<i>wile moli </i>:: suicidal',
'<i>wile mute ike </i>:: to want too much, greedy',
'<i>wile mute </i>:: to crave, really want',
'<i>wile pali e ijo </i>:: bored, wanting to do something',
'<i>wile pana e pona tawa jan </i>:: helpful to someone',
'<i>wile pi jan ike li pakala e ijo </i>:: The desires of evil people mess things up',
'<i>wile pona </i>:: to have good intentions, mean well',
'<i>wile sona li mute e sona </i>:: Curiosity feeds wisdom; one learns by asking questions',
'<i>wile unpa e meli e mije </i>:: to be sexually attracted to women and men',
'<i>wile unpa e meli </i>:: to be sexually attracted to women',
'<i>wile unpa e mije </i>:: to be sexually attracted to men',
'<i>wile unpa </i>:: horny, lustful',
'<i>wile </i>:: [v] to want, need, wish, have to, must, will, should  [n] desire, need, will  [mod] necessary',

];
